//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class CityFlow {
  public static SWIGTYPE_p_std__string ARGS_END {
    get {
      SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CityFlowPINVOKE.ARGS_END_get(), true);
      return ret;
    } 
  }

  public static SWIGTYPE_p_std__string remove_character(SWIGTYPE_p_std__string str, char c) {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CityFlowPINVOKE.remove_character(SWIGTYPE_p_std__string.getCPtr(str), c), true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_std__vectorT_std__string_t split_str(SWIGTYPE_p_std__string s, SWIGTYPE_p_std__string delimiter) {
    SWIGTYPE_p_std__vectorT_std__string_t ret = new SWIGTYPE_p_std__vectorT_std__string_t(CityFlowPINVOKE.split_str__SWIG_0(SWIGTYPE_p_std__string.getCPtr(s), SWIGTYPE_p_std__string.getCPtr(delimiter)), true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_std__vectorT_std__string_t split_str(SWIGTYPE_p_std__string s) {
    SWIGTYPE_p_std__vectorT_std__string_t ret = new SWIGTYPE_p_std__vectorT_std__string_t(CityFlowPINVOKE.split_str__SWIG_1(SWIGTYPE_p_std__string.getCPtr(s)), true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double eps {
    get {
      double ret = CityFlowPINVOKE.eps_get();
      return ret;
    } 
  }

  public static uint JSON_BUFFER_SIZE {
    get {
      uint ret = CityFlowPINVOKE.JSON_BUFFER_SIZE_get();
      return ret;
    } 
  }

  public static Point MultiplyValue(Point A, double k) {
    Point ret = new Point(CityFlowPINVOKE.MultiplyValue(Point.getCPtr(A), k), true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static Point SubtractPoint(Point A, Point B) {
    Point ret = new Point(CityFlowPINVOKE.SubtractPoint(Point.getCPtr(A), Point.getCPtr(B)), true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static Point AddPoint(Point A, Point B) {
    Point ret = new Point(CityFlowPINVOKE.AddPoint(Point.getCPtr(A), Point.getCPtr(B)), true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static Point Negative(Point A) {
    Point ret = new Point(CityFlowPINVOKE.Negative(Point.getCPtr(A)), true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double crossMultiply(Point A, Point B) {
    double ret = CityFlowPINVOKE.crossMultiply(Point.getCPtr(A), Point.getCPtr(B));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double dotMultiply(Point A, Point B) {
    double ret = CityFlowPINVOKE.dotMultiply(Point.getCPtr(A), Point.getCPtr(B));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double calcAng(Point A, Point B) {
    double ret = CityFlowPINVOKE.calcAng(Point.getCPtr(A), Point.getCPtr(B));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static Point calcIntersectPoint(Point A, Point B, Point C, Point D) {
    Point ret = new Point(CityFlowPINVOKE.calcIntersectPoint(Point.getCPtr(A), Point.getCPtr(B), Point.getCPtr(C), Point.getCPtr(D)), true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool onSegment(Point A, Point B, Point P) {
    bool ret = CityFlowPINVOKE.onSegment(Point.getCPtr(A), Point.getCPtr(B), Point.getCPtr(P));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double max2double(double x, double y) {
    double ret = CityFlowPINVOKE.max2double(x, y);
    return ret;
  }

  public static double min2double(double x, double y) {
    double ret = CityFlowPINVOKE.min2double(x, y);
    return ret;
  }

  public static SWIGTYPE_p_std__string double2string(double x) {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CityFlowPINVOKE.double2string(x), true);
    return ret;
  }

  public static SWIGTYPE_p_std__vectorT_int_t generateRandomIndices(uint n, SWIGTYPE_p_std__mt19937 rnd) {
    SWIGTYPE_p_std__vectorT_int_t ret = new SWIGTYPE_p_std__vectorT_int_t(CityFlowPINVOKE.generateRandomIndices(n, SWIGTYPE_p_std__mt19937.getCPtr(rnd)), true);
    return ret;
  }

  public static bool readJsonFromFile(SWIGTYPE_p_std__string filename, SWIGTYPE_p_rapidjson__Document document) {
    bool ret = CityFlowPINVOKE.readJsonFromFile(SWIGTYPE_p_std__string.getCPtr(filename), SWIGTYPE_p_rapidjson__Document.getCPtr(document));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool writeJsonToFile(SWIGTYPE_p_std__string filename, SWIGTYPE_p_rapidjson__Document document) {
    bool ret = CityFlowPINVOKE.writeJsonToFile(SWIGTYPE_p_std__string.getCPtr(filename), SWIGTYPE_p_rapidjson__Document.getCPtr(document));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_rapidjson__Value getJsonMemberValue(SWIGTYPE_p_std__string name, SWIGTYPE_p_rapidjson__Value object_) {
    SWIGTYPE_p_rapidjson__Value ret = new SWIGTYPE_p_rapidjson__Value(CityFlowPINVOKE.getJsonMemberValue(SWIGTYPE_p_std__string.getCPtr(name), SWIGTYPE_p_rapidjson__Value.getCPtr(object_)), false);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_rapidjson__Value getJsonMemberObject(SWIGTYPE_p_std__string name, SWIGTYPE_p_rapidjson__Value object_) {
    SWIGTYPE_p_rapidjson__Value ret = new SWIGTYPE_p_rapidjson__Value(CityFlowPINVOKE.getJsonMemberObject(SWIGTYPE_p_std__string.getCPtr(name), SWIGTYPE_p_rapidjson__Value.getCPtr(object_)), false);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_rapidjson__Value getJsonMemberArray(SWIGTYPE_p_std__string name, SWIGTYPE_p_rapidjson__Value object_) {
    SWIGTYPE_p_rapidjson__Value ret = new SWIGTYPE_p_rapidjson__Value(CityFlowPINVOKE.getJsonMemberArray(SWIGTYPE_p_std__string.getCPtr(name), SWIGTYPE_p_rapidjson__Value.getCPtr(object_)), false);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
