//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class ControlInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ControlInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ControlInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ControlInfo obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ControlInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_ControlInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double speed {
    set {
      CityFlowPINVOKE.ControlInfo_speed_set(swigCPtr, value);
    } 
    get {
      double ret = CityFlowPINVOKE.ControlInfo_speed_get(swigCPtr);
      return ret;
    } 
  }

  public double changingSpeed {
    set {
      CityFlowPINVOKE.ControlInfo_changingSpeed_set(swigCPtr, value);
    } 
    get {
      double ret = CityFlowPINVOKE.ControlInfo_changingSpeed_get(swigCPtr);
      return ret;
    } 
  }

  public Lane nextLane {
    set {
      CityFlowPINVOKE.ControlInfo_nextLane_set(swigCPtr, Lane.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CityFlowPINVOKE.ControlInfo_nextLane_get(swigCPtr);
      Lane ret = (cPtr == global::System.IntPtr.Zero) ? null : new Lane(cPtr, false);
      return ret;
    } 
  }

  public bool waitingForChangingLane {
    set {
      CityFlowPINVOKE.ControlInfo_waitingForChangingLane_set(swigCPtr, value);
    } 
    get {
      bool ret = CityFlowPINVOKE.ControlInfo_waitingForChangingLane_get(swigCPtr);
      return ret;
    } 
  }

  public bool collision {
    set {
      CityFlowPINVOKE.ControlInfo_collision_set(swigCPtr, value);
    } 
    get {
      bool ret = CityFlowPINVOKE.ControlInfo_collision_get(swigCPtr);
      return ret;
    } 
  }

  public ControlInfo() : this(CityFlowPINVOKE.new_ControlInfo(), true) {
  }

}

}
