//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class Cross : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Cross(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Cross obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Cross obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Cross() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_Cross(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double getLeaveDistance() {
    double ret = CityFlowPINVOKE.Cross_getLeaveDistance(swigCPtr);
    return ret;
  }

  public double getArriveDistance() {
    double ret = CityFlowPINVOKE.Cross_getArriveDistance(swigCPtr);
    return ret;
  }

  public void notify(LaneLink laneLink, Vehicle vehicle, double notifyDistance) {
    CityFlowPINVOKE.Cross_notify(swigCPtr, LaneLink.getCPtr(laneLink), Vehicle.getCPtr(vehicle), notifyDistance);
  }

  public bool canPass(Vehicle vehicle, LaneLink laneLink, double distanceToLaneLinkStart) {
    bool ret = CityFlowPINVOKE.Cross_canPass(swigCPtr, Vehicle.getCPtr(vehicle), LaneLink.getCPtr(laneLink), distanceToLaneLinkStart);
    return ret;
  }

  public void clearNotify() {
    CityFlowPINVOKE.Cross_clearNotify(swigCPtr);
  }

  public Vehicle getFoeVehicle(LaneLink laneLink) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Cross_getFoeVehicle(swigCPtr, LaneLink.getCPtr(laneLink));
    Vehicle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vehicle(cPtr, false);
    return ret;
  }

  public double getDistanceByLane(LaneLink laneLink) {
    double ret = CityFlowPINVOKE.Cross_getDistanceByLane(swigCPtr, LaneLink.getCPtr(laneLink));
    return ret;
  }

  public double getNotifyDistanceByLane(LaneLink laneLink) {
    double ret = CityFlowPINVOKE.Cross_getNotifyDistanceByLane(swigCPtr, LaneLink.getCPtr(laneLink));
    return ret;
  }

  public double getSafeDistanceByLane(LaneLink laneLink) {
    double ret = CityFlowPINVOKE.Cross_getSafeDistanceByLane(swigCPtr, LaneLink.getCPtr(laneLink));
    return ret;
  }

  public double getAng() {
    double ret = CityFlowPINVOKE.Cross_getAng(swigCPtr);
    return ret;
  }

  public LaneLink getLaneLink(int i) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Cross_getLaneLink(swigCPtr, i);
    LaneLink ret = (cPtr == global::System.IntPtr.Zero) ? null : new LaneLink(cPtr, false);
    return ret;
  }

  public void reset() {
    CityFlowPINVOKE.Cross_reset(swigCPtr);
  }

  public Cross() : this(CityFlowPINVOKE.new_Cross(), true) {
  }

}

}
