//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class Intersection : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Intersection(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Intersection obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Intersection obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Intersection() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_Intersection(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SWIGTYPE_p_std__string getId() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CityFlowPINVOKE.Intersection_getId(swigCPtr), true);
    return ret;
  }

  public TrafficLight getTrafficLight() {
    TrafficLight ret = new TrafficLight(CityFlowPINVOKE.Intersection_getTrafficLight__SWIG_0(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_CityFlow__Road_p_t getRoads() {
    SWIGTYPE_p_std__vectorT_CityFlow__Road_p_t ret = new SWIGTYPE_p_std__vectorT_CityFlow__Road_p_t(CityFlowPINVOKE.Intersection_getRoads__SWIG_0(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_RoadLink_t getRoadLinks() {
    SWIGTYPE_p_std__vectorT_RoadLink_t ret = new SWIGTYPE_p_std__vectorT_RoadLink_t(CityFlowPINVOKE.Intersection_getRoadLinks__SWIG_0(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_CityFlow__Cross_t getCrosses() {
    SWIGTYPE_p_std__vectorT_CityFlow__Cross_t ret = new SWIGTYPE_p_std__vectorT_CityFlow__Cross_t(CityFlowPINVOKE.Intersection_getCrosses(swigCPtr), false);
    return ret;
  }

  public bool isVirtualIntersection() {
    bool ret = CityFlowPINVOKE.Intersection_isVirtualIntersection(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_CityFlow__LaneLink_p_t getLaneLinks() {
    SWIGTYPE_p_std__vectorT_CityFlow__LaneLink_p_t ret = new SWIGTYPE_p_std__vectorT_CityFlow__LaneLink_p_t(CityFlowPINVOKE.Intersection_getLaneLinks(swigCPtr), false);
    return ret;
  }

  public void reset() {
    CityFlowPINVOKE.Intersection_reset(swigCPtr);
  }

  public SWIGTYPE_p_std__vectorT_Point_t getOutline() {
    SWIGTYPE_p_std__vectorT_Point_t ret = new SWIGTYPE_p_std__vectorT_Point_t(CityFlowPINVOKE.Intersection_getOutline(swigCPtr), true);
    return ret;
  }

  public bool isImplicitIntersection() {
    bool ret = CityFlowPINVOKE.Intersection_isImplicitIntersection(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_Point getPosition() {
    SWIGTYPE_p_Point ret = new SWIGTYPE_p_Point(CityFlowPINVOKE.Intersection_getPosition(swigCPtr), false);
    return ret;
  }

  public Intersection() : this(CityFlowPINVOKE.new_Intersection(), true) {
  }

}

}
