//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class LaneInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LaneInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LaneInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(LaneInfo obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~LaneInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_LaneInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Road road {
    set {
      CityFlowPINVOKE.LaneInfo_road_set(swigCPtr, Road.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CityFlowPINVOKE.LaneInfo_road_get(swigCPtr);
      Road ret = (cPtr == global::System.IntPtr.Zero) ? null : new Road(cPtr, false);
      return ret;
    } 
  }

  public int LaneNumber {
    set {
      CityFlowPINVOKE.LaneInfo_LaneNumber_set(swigCPtr, value);
    } 
    get {
      int ret = CityFlowPINVOKE.LaneInfo_LaneNumber_get(swigCPtr);
      return ret;
    } 
  }

  public double pos {
    set {
      CityFlowPINVOKE.LaneInfo_pos_set(swigCPtr, value);
    } 
    get {
      double ret = CityFlowPINVOKE.LaneInfo_pos_get(swigCPtr);
      return ret;
    } 
  }

  public LaneInfo() : this(CityFlowPINVOKE.new_LaneInfo(), true) {
  }

}

}
