//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class LaneLink : Drivable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal LaneLink(global::System.IntPtr cPtr, bool cMemoryOwn) : base(CityFlowPINVOKE.LaneLink_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LaneLink obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(LaneLink obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_LaneLink(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public LaneLink() : this(CityFlowPINVOKE.new_LaneLink(), true) {
  }

  public RoadLink getRoadLink() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.LaneLink_getRoadLink(swigCPtr);
    RoadLink ret = (cPtr == global::System.IntPtr.Zero) ? null : new RoadLink(cPtr, false);
    return ret;
  }

  public RoadLinkType getRoadLinkType() {
    RoadLinkType ret = (RoadLinkType)CityFlowPINVOKE.LaneLink_getRoadLinkType(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_CityFlow__Cross_p_t getCrosses() {
    SWIGTYPE_p_std__vectorT_CityFlow__Cross_p_t ret = new SWIGTYPE_p_std__vectorT_CityFlow__Cross_p_t(CityFlowPINVOKE.LaneLink_getCrosses__SWIG_0(swigCPtr), false);
    return ret;
  }

  public Lane getStartLane() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.LaneLink_getStartLane(swigCPtr);
    Lane ret = (cPtr == global::System.IntPtr.Zero) ? null : new Lane(cPtr, false);
    return ret;
  }

  public Lane getEndLane() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.LaneLink_getEndLane(swigCPtr);
    Lane ret = (cPtr == global::System.IntPtr.Zero) ? null : new Lane(cPtr, false);
    return ret;
  }

  public bool isAvailable() {
    bool ret = CityFlowPINVOKE.LaneLink_isAvailable(swigCPtr);
    return ret;
  }

  public bool isTurn() {
    bool ret = CityFlowPINVOKE.LaneLink_isTurn(swigCPtr);
    return ret;
  }

  public void reset() {
    CityFlowPINVOKE.LaneLink_reset(swigCPtr);
  }

  public override SWIGTYPE_p_std__string getId() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CityFlowPINVOKE.LaneLink_getId(swigCPtr), true);
    return ret;
  }

}

}
