//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class Lane : Drivable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal Lane(global::System.IntPtr cPtr, bool cMemoryOwn) : base(CityFlowPINVOKE.Lane_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Lane obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Lane obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_Lane(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public Lane() : this(CityFlowPINVOKE.new_Lane__SWIG_0(), true) {
  }

  public Lane(double width, double maxSpeed, int laneIndex, Road belongRoad) : this(CityFlowPINVOKE.new_Lane__SWIG_1(width, maxSpeed, laneIndex, Road.getCPtr(belongRoad)), true) {
  }

  public override SWIGTYPE_p_std__string getId() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CityFlowPINVOKE.Lane_getId(swigCPtr), true);
    return ret;
  }

  public Road getBelongRoad() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Lane_getBelongRoad(swigCPtr);
    Road ret = (cPtr == global::System.IntPtr.Zero) ? null : new Road(cPtr, false);
    return ret;
  }

  public bool available(Vehicle vehicle) {
    bool ret = CityFlowPINVOKE.Lane_available(swigCPtr, Vehicle.getCPtr(vehicle));
    return ret;
  }

  public bool canEnter(Vehicle vehicle) {
    bool ret = CityFlowPINVOKE.Lane_canEnter(swigCPtr, Vehicle.getCPtr(vehicle));
    return ret;
  }

  public uint getLaneIndex() {
    uint ret = CityFlowPINVOKE.Lane_getLaneIndex(swigCPtr);
    return ret;
  }

  public Lane getInnerLane() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Lane_getInnerLane(swigCPtr);
    Lane ret = (cPtr == global::System.IntPtr.Zero) ? null : new Lane(cPtr, false);
    return ret;
  }

  public Lane getOuterLane() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Lane_getOuterLane(swigCPtr);
    Lane ret = (cPtr == global::System.IntPtr.Zero) ? null : new Lane(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_CityFlow__LaneLink_p_t getLaneLinks() {
    SWIGTYPE_p_std__vectorT_CityFlow__LaneLink_p_t ret = new SWIGTYPE_p_std__vectorT_CityFlow__LaneLink_p_t(CityFlowPINVOKE.Lane_getLaneLinks__SWIG_0(swigCPtr), false);
    return ret;
  }

  public Intersection getStartIntersection() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Lane_getStartIntersection(swigCPtr);
    Intersection ret = (cPtr == global::System.IntPtr.Zero) ? null : new Intersection(cPtr, false);
    return ret;
  }

  public Intersection getEndIntersection() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Lane_getEndIntersection(swigCPtr);
    Intersection ret = (cPtr == global::System.IntPtr.Zero) ? null : new Intersection(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_CityFlow__LaneLink_p_t getLaneLinksToRoad(Road road) {
    SWIGTYPE_p_std__vectorT_CityFlow__LaneLink_p_t ret = new SWIGTYPE_p_std__vectorT_CityFlow__LaneLink_p_t(CityFlowPINVOKE.Lane_getLaneLinksToRoad(swigCPtr, Road.getCPtr(road)), true);
    return ret;
  }

  public void reset() {
    CityFlowPINVOKE.Lane_reset(swigCPtr);
  }

  public SWIGTYPE_p_std__dequeT_CityFlow__Vehicle_p_t getWaitingBuffer() {
    SWIGTYPE_p_std__dequeT_CityFlow__Vehicle_p_t ret = new SWIGTYPE_p_std__dequeT_CityFlow__Vehicle_p_t(CityFlowPINVOKE.Lane_getWaitingBuffer__SWIG_0(swigCPtr), false);
    return ret;
  }

  public void pushWaitingVehicle(Vehicle vehicle) {
    CityFlowPINVOKE.Lane_pushWaitingVehicle(swigCPtr, Vehicle.getCPtr(vehicle));
  }

  public void buildSegmentation(uint numSegs) {
    CityFlowPINVOKE.Lane_buildSegmentation(swigCPtr, numSegs);
  }

  public void initSegments() {
    CityFlowPINVOKE.Lane_initSegments(swigCPtr);
  }

  public Segment getSegment(uint index) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Lane_getSegment__SWIG_0(swigCPtr, index);
    Segment ret = (cPtr == global::System.IntPtr.Zero) ? null : new Segment(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_CityFlow__Segment_t getSegments() {
    SWIGTYPE_p_std__vectorT_CityFlow__Segment_t ret = new SWIGTYPE_p_std__vectorT_CityFlow__Segment_t(CityFlowPINVOKE.Lane_getSegments__SWIG_0(swigCPtr), false);
    return ret;
  }

  public uint getSegmentNum() {
    uint ret = CityFlowPINVOKE.Lane_getSegmentNum(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_CityFlow__Vehicle_p_t getVehiclesBeforeDistance(double dis, uint segmentIndex, double deltaDis) {
    SWIGTYPE_p_std__vectorT_CityFlow__Vehicle_p_t ret = new SWIGTYPE_p_std__vectorT_CityFlow__Vehicle_p_t(CityFlowPINVOKE.Lane_getVehiclesBeforeDistance__SWIG_0(swigCPtr, dis, segmentIndex, deltaDis), true);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_CityFlow__Vehicle_p_t getVehiclesBeforeDistance(double dis, uint segmentIndex) {
    SWIGTYPE_p_std__vectorT_CityFlow__Vehicle_p_t ret = new SWIGTYPE_p_std__vectorT_CityFlow__Vehicle_p_t(CityFlowPINVOKE.Lane_getVehiclesBeforeDistance__SWIG_1(swigCPtr, dis, segmentIndex), true);
    return ret;
  }

  public void updateHistory() {
    CityFlowPINVOKE.Lane_updateHistory(swigCPtr);
  }

  public int getHistoryVehicleNum() {
    int ret = CityFlowPINVOKE.Lane_getHistoryVehicleNum(swigCPtr);
    return ret;
  }

  public double getHistoryAverageSpeed() {
    double ret = CityFlowPINVOKE.Lane_getHistoryAverageSpeed(swigCPtr);
    return ret;
  }

  public Vehicle getVehicleBeforeDistance(double dis, uint segmentIndex) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Lane_getVehicleBeforeDistance(swigCPtr, dis, segmentIndex);
    Vehicle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vehicle(cPtr, false);
    return ret;
  }

  public Vehicle getVehicleAfterDistance(double dis, uint segmentIndex) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Lane_getVehicleAfterDistance(swigCPtr, dis, segmentIndex);
    Vehicle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vehicle(cPtr, false);
    return ret;
  }

}

}
