//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public enum OptionType {
  LONG_OPT = 0,
  SHORT_OPT,
  POSITIONAL_OPT,
  EMPTY_OPT
}

}
