//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class Option : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Option(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Option obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Option obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Option() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_Option(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Option() : this(CityFlowPINVOKE.new_Option(), true) {
  }

  public void help_doc() {
    CityFlowPINVOKE.Option_help_doc(swigCPtr);
  }

  public SWIGTYPE_p_bool found() {
    SWIGTYPE_p_bool ret = new SWIGTYPE_p_bool(CityFlowPINVOKE.Option_found(swigCPtr), false);
    return ret;
  }

  public Option required(bool req) {
    Option ret = new Option(CityFlowPINVOKE.Option_required__SWIG_0(swigCPtr, req), false);
    return ret;
  }

  public SWIGTYPE_p_bool required() {
    SWIGTYPE_p_bool ret = new SWIGTYPE_p_bool(CityFlowPINVOKE.Option_required__SWIG_1(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__string short_flag() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CityFlowPINVOKE.Option_short_flag(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__string long_flag() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CityFlowPINVOKE.Option_long_flag(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__string pos_flag() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CityFlowPINVOKE.Option_pos_flag(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__string m_short_flag {
    set {
      CityFlowPINVOKE.Option_m_short_flag_set(swigCPtr, SWIGTYPE_p_std__string.getCPtr(value));
      if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CityFlowPINVOKE.Option_m_short_flag_get(swigCPtr), true);
      if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_std__string m_long_flag {
    set {
      CityFlowPINVOKE.Option_m_long_flag_set(swigCPtr, SWIGTYPE_p_std__string.getCPtr(value));
      if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CityFlowPINVOKE.Option_m_long_flag_get(swigCPtr), true);
      if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_std__string m_pos_flag {
    set {
      CityFlowPINVOKE.Option_m_pos_flag_set(swigCPtr, SWIGTYPE_p_std__string.getCPtr(value));
      if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CityFlowPINVOKE.Option_m_pos_flag_get(swigCPtr), true);
      if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_optionparser__StorageMode mode() {
    SWIGTYPE_p_optionparser__StorageMode ret = new SWIGTYPE_p_optionparser__StorageMode(CityFlowPINVOKE.Option_mode__SWIG_0(swigCPtr), false);
    return ret;
  }

  public Option mode(StorageMode mode) {
    Option ret = new Option(CityFlowPINVOKE.Option_mode__SWIG_1(swigCPtr, (int)mode), false);
    return ret;
  }

  public SWIGTYPE_p_std__string help() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CityFlowPINVOKE.Option_help__SWIG_0(swigCPtr), false);
    return ret;
  }

  public Option help(SWIGTYPE_p_std__string help) {
    Option ret = new Option(CityFlowPINVOKE.Option_help__SWIG_1(swigCPtr, SWIGTYPE_p_std__string.getCPtr(help)), false);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__string dest() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CityFlowPINVOKE.Option_dest__SWIG_0(swigCPtr), false);
    return ret;
  }

  public Option dest(SWIGTYPE_p_std__string dest) {
    Option ret = new Option(CityFlowPINVOKE.Option_dest__SWIG_1(swigCPtr, SWIGTYPE_p_std__string.getCPtr(dest)), false);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__string default_value() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CityFlowPINVOKE.Option_default_value__SWIG_0(swigCPtr), false);
    return ret;
  }

  public Option default_value(SWIGTYPE_p_std__string default_value) {
    Option ret = new Option(CityFlowPINVOKE.Option_default_value__SWIG_1(swigCPtr, SWIGTYPE_p_std__string.getCPtr(default_value)), false);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Option default_value(string default_value) {
    Option ret = new Option(CityFlowPINVOKE.Option_default_value__SWIG_2(swigCPtr, default_value), false);
    return ret;
  }

  public bool m_found {
    set {
      CityFlowPINVOKE.Option_m_found_set(swigCPtr, value);
    } 
    get {
      bool ret = CityFlowPINVOKE.Option_m_found_get(swigCPtr);
      return ret;
    } 
  }

  public bool m_required {
    set {
      CityFlowPINVOKE.Option_m_required_set(swigCPtr, value);
    } 
    get {
      bool ret = CityFlowPINVOKE.Option_m_required_get(swigCPtr);
      return ret;
    } 
  }

  public StorageMode m_mode {
    set {
      CityFlowPINVOKE.Option_m_mode_set(swigCPtr, (int)value);
    } 
    get {
      StorageMode ret = (StorageMode)CityFlowPINVOKE.Option_m_mode_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_std__string m_help {
    set {
      CityFlowPINVOKE.Option_m_help_set(swigCPtr, SWIGTYPE_p_std__string.getCPtr(value));
      if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CityFlowPINVOKE.Option_m_help_get(swigCPtr), true);
      if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_std__string m_dest {
    set {
      CityFlowPINVOKE.Option_m_dest_set(swigCPtr, SWIGTYPE_p_std__string.getCPtr(value));
      if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CityFlowPINVOKE.Option_m_dest_get(swigCPtr), true);
      if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_std__string m_default_value {
    set {
      CityFlowPINVOKE.Option_m_default_value_set(swigCPtr, SWIGTYPE_p_std__string.getCPtr(value));
      if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CityFlowPINVOKE.Option_m_default_value_get(swigCPtr), true);
      if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public static OptionType get_type(SWIGTYPE_p_std__string opt) {
    OptionType ret = (OptionType)CityFlowPINVOKE.Option_get_type(SWIGTYPE_p_std__string.getCPtr(opt));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_std__string get_destination(SWIGTYPE_p_std__string opt1, SWIGTYPE_p_std__string opt2, OptionType ft, OptionType st) {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CityFlowPINVOKE.Option_get_destination(SWIGTYPE_p_std__string.getCPtr(opt1), SWIGTYPE_p_std__string.getCPtr(opt2), (int)ft, (int)st), true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
