//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class Point : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Point(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Point obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Point obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Point() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_Point(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double x {
    set {
      CityFlowPINVOKE.Point_x_set(swigCPtr, value);
    } 
    get {
      double ret = CityFlowPINVOKE.Point_x_get(swigCPtr);
      return ret;
    } 
  }

  public double y {
    set {
      CityFlowPINVOKE.Point_y_set(swigCPtr, value);
    } 
    get {
      double ret = CityFlowPINVOKE.Point_y_get(swigCPtr);
      return ret;
    } 
  }

  public static int sign(double x) {
    int ret = CityFlowPINVOKE.Point_sign(x);
    return ret;
  }

  public Point() : this(CityFlowPINVOKE.new_Point__SWIG_0(), true) {
  }

  public Point(double x, double y) : this(CityFlowPINVOKE.new_Point__SWIG_1(x, y), true) {
  }

  public double len() {
    double ret = CityFlowPINVOKE.Point_len(swigCPtr);
    return ret;
  }

  public Point normal() {
    Point ret = new Point(CityFlowPINVOKE.Point_normal(swigCPtr), true);
    return ret;
  }

  public Point unit() {
    Point ret = new Point(CityFlowPINVOKE.Point_unit(swigCPtr), true);
    return ret;
  }

  public double ang() {
    double ret = CityFlowPINVOKE.Point_ang(swigCPtr);
    return ret;
  }

  public static readonly double eps = CityFlowPINVOKE.Point_eps_get();
}

}
