//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class Road : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Road(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Road obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Road obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Road() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_Road(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SWIGTYPE_p_std__string getId() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CityFlowPINVOKE.Road_getId(swigCPtr), true);
    return ret;
  }

  public Intersection getStartIntersection() {
    Intersection ret = new Intersection(CityFlowPINVOKE.Road_getStartIntersection(swigCPtr), false);
    return ret;
  }

  public Intersection getEndIntersection() {
    Intersection ret = new Intersection(CityFlowPINVOKE.Road_getEndIntersection(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_CityFlow__Lane_t getLanes() {
    SWIGTYPE_p_std__vectorT_CityFlow__Lane_t ret = new SWIGTYPE_p_std__vectorT_CityFlow__Lane_t(CityFlowPINVOKE.Road_getLanes__SWIG_0(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_CityFlow__Lane_p_t getLanePointers() {
    SWIGTYPE_p_std__vectorT_CityFlow__Lane_p_t ret = new SWIGTYPE_p_std__vectorT_CityFlow__Lane_p_t(CityFlowPINVOKE.Road_getLanePointers(swigCPtr), false);
    return ret;
  }

  public void buildSegmentationByInterval(double interval) {
    CityFlowPINVOKE.Road_buildSegmentationByInterval(swigCPtr, interval);
  }

  public bool connectedToRoad(Road road) {
    bool ret = CityFlowPINVOKE.Road_connectedToRoad(swigCPtr, Road.getCPtr(road));
    return ret;
  }

  public void reset() {
    CityFlowPINVOKE.Road_reset(swigCPtr);
  }

  public double getWidth() {
    double ret = CityFlowPINVOKE.Road_getWidth(swigCPtr);
    return ret;
  }

  public double getLength() {
    double ret = CityFlowPINVOKE.Road_getLength(swigCPtr);
    return ret;
  }

  public double averageLength() {
    double ret = CityFlowPINVOKE.Road_averageLength(swigCPtr);
    return ret;
  }

  public double getAverageSpeed() {
    double ret = CityFlowPINVOKE.Road_getAverageSpeed(swigCPtr);
    return ret;
  }

  public double getAverageDuration() {
    double ret = CityFlowPINVOKE.Road_getAverageDuration(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_CityFlow__Vehicle_p_t getPlanRouteBuffer() {
    SWIGTYPE_p_std__vectorT_CityFlow__Vehicle_p_t ret = new SWIGTYPE_p_std__vectorT_CityFlow__Vehicle_p_t(CityFlowPINVOKE.Road_getPlanRouteBuffer(swigCPtr), false);
    return ret;
  }

  public void addPlanRouteVehicle(Vehicle vehicle) {
    CityFlowPINVOKE.Road_addPlanRouteVehicle(swigCPtr, Vehicle.getCPtr(vehicle));
  }

  public void clearPlanRouteBuffer() {
    CityFlowPINVOKE.Road_clearPlanRouteBuffer(swigCPtr);
  }

  public Road() : this(CityFlowPINVOKE.new_Road(), true) {
  }

}

}
