//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class RoadNet : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RoadNet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RoadNet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(RoadNet obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~RoadNet() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_RoadNet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public bool loadFromJson(SWIGTYPE_p_std__string jsonFileName) {
    bool ret = CityFlowPINVOKE.RoadNet_loadFromJson(swigCPtr, SWIGTYPE_p_std__string.getCPtr(jsonFileName));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_rapidjson__Value convertToJson(SWIGTYPE_p_rapidjson__Document__AllocatorType allocator) {
    SWIGTYPE_p_rapidjson__Value ret = new SWIGTYPE_p_rapidjson__Value(CityFlowPINVOKE.RoadNet_convertToJson(swigCPtr, SWIGTYPE_p_rapidjson__Document__AllocatorType.getCPtr(allocator)), true);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_CityFlow__Road_t getRoads() {
    SWIGTYPE_p_std__vectorT_CityFlow__Road_t ret = new SWIGTYPE_p_std__vectorT_CityFlow__Road_t(CityFlowPINVOKE.RoadNet_getRoads__SWIG_0(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_CityFlow__Intersection_t getIntersections() {
    SWIGTYPE_p_std__vectorT_CityFlow__Intersection_t ret = new SWIGTYPE_p_std__vectorT_CityFlow__Intersection_t(CityFlowPINVOKE.RoadNet_getIntersections__SWIG_0(swigCPtr), false);
    return ret;
  }

  public Road getRoadById(SWIGTYPE_p_std__string id) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.RoadNet_getRoadById(swigCPtr, SWIGTYPE_p_std__string.getCPtr(id));
    Road ret = (cPtr == global::System.IntPtr.Zero) ? null : new Road(cPtr, false);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Intersection getIntersectionById(SWIGTYPE_p_std__string id) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.RoadNet_getIntersectionById(swigCPtr, SWIGTYPE_p_std__string.getCPtr(id));
    Intersection ret = (cPtr == global::System.IntPtr.Zero) ? null : new Intersection(cPtr, false);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Drivable getDrivableById(SWIGTYPE_p_std__string id) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.RoadNet_getDrivableById(swigCPtr, SWIGTYPE_p_std__string.getCPtr(id));
    Drivable ret = (cPtr == global::System.IntPtr.Zero) ? null : new Drivable(cPtr, false);
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_CityFlow__Lane_p_t getLanes() {
    SWIGTYPE_p_std__vectorT_CityFlow__Lane_p_t ret = new SWIGTYPE_p_std__vectorT_CityFlow__Lane_p_t(CityFlowPINVOKE.RoadNet_getLanes(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_CityFlow__LaneLink_p_t getLaneLinks() {
    SWIGTYPE_p_std__vectorT_CityFlow__LaneLink_p_t ret = new SWIGTYPE_p_std__vectorT_CityFlow__LaneLink_p_t(CityFlowPINVOKE.RoadNet_getLaneLinks(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_CityFlow__Drivable_p_t getDrivables() {
    SWIGTYPE_p_std__vectorT_CityFlow__Drivable_p_t ret = new SWIGTYPE_p_std__vectorT_CityFlow__Drivable_p_t(CityFlowPINVOKE.RoadNet_getDrivables(swigCPtr), false);
    return ret;
  }

  public void reset() {
    CityFlowPINVOKE.RoadNet_reset(swigCPtr);
  }

  public RoadNet() : this(CityFlowPINVOKE.new_RoadNet(), true) {
  }

}

}
