//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class RoadLink : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RoadLink(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RoadLink obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(RoadLink obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~RoadLink() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_RoadLink(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SWIGTYPE_p_std__vectorT_CityFlow__LaneLink_t getLaneLinks() {
    SWIGTYPE_p_std__vectorT_CityFlow__LaneLink_t ret = new SWIGTYPE_p_std__vectorT_CityFlow__LaneLink_t(CityFlowPINVOKE.RoadLink_getLaneLinks__SWIG_0(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_CityFlow__LaneLink_p_t getLaneLinkPointers() {
    SWIGTYPE_p_std__vectorT_CityFlow__LaneLink_p_t ret = new SWIGTYPE_p_std__vectorT_CityFlow__LaneLink_p_t(CityFlowPINVOKE.RoadLink_getLaneLinkPointers(swigCPtr), false);
    return ret;
  }

  public Road getStartRoad() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.RoadLink_getStartRoad(swigCPtr);
    Road ret = (cPtr == global::System.IntPtr.Zero) ? null : new Road(cPtr, false);
    return ret;
  }

  public Road getEndRoad() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.RoadLink_getEndRoad(swigCPtr);
    Road ret = (cPtr == global::System.IntPtr.Zero) ? null : new Road(cPtr, false);
    return ret;
  }

  public bool isAvailable() {
    bool ret = CityFlowPINVOKE.RoadLink_isAvailable(swigCPtr);
    return ret;
  }

  public bool isTurn() {
    bool ret = CityFlowPINVOKE.RoadLink_isTurn(swigCPtr);
    return ret;
  }

  public void reset() {
    CityFlowPINVOKE.RoadLink_reset(swigCPtr);
  }

  public RoadLink() : this(CityFlowPINVOKE.new_RoadLink(), true) {
  }

}

}
