//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class Router : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Router(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Router obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Router obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Router() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_Router(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Router(Router other) : this(CityFlowPINVOKE.new_Router__SWIG_0(Router.getCPtr(other)), true) {
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public Router(Vehicle vehicle, SWIGTYPE_p_std__shared_ptrT_CityFlow__Route_const_t route, SWIGTYPE_p_std__mt19937 rnd) : this(CityFlowPINVOKE.new_Router__SWIG_1(Vehicle.getCPtr(vehicle), SWIGTYPE_p_std__shared_ptrT_CityFlow__Route_const_t.getCPtr(route), SWIGTYPE_p_std__mt19937.getCPtr(rnd)), true) {
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public Road getFirstRoad() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Router_getFirstRoad(swigCPtr);
    Road ret = (cPtr == global::System.IntPtr.Zero) ? null : new Road(cPtr, false);
    return ret;
  }

  public Drivable getFirstDrivable() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Router_getFirstDrivable(swigCPtr);
    Drivable ret = (cPtr == global::System.IntPtr.Zero) ? null : new Drivable(cPtr, false);
    return ret;
  }

  public Drivable getNextDrivable(uint i) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Router_getNextDrivable__SWIG_0(swigCPtr, i);
    Drivable ret = (cPtr == global::System.IntPtr.Zero) ? null : new Drivable(cPtr, false);
    return ret;
  }

  public Drivable getNextDrivable() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Router_getNextDrivable__SWIG_1(swigCPtr);
    Drivable ret = (cPtr == global::System.IntPtr.Zero) ? null : new Drivable(cPtr, false);
    return ret;
  }

  public Drivable getNextDrivable(Drivable curDrivable) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Router_getNextDrivable__SWIG_2(swigCPtr, Drivable.getCPtr(curDrivable));
    Drivable ret = (cPtr == global::System.IntPtr.Zero) ? null : new Drivable(cPtr, false);
    return ret;
  }

  public void update() {
    CityFlowPINVOKE.Router_update(swigCPtr);
  }

  public bool isLastRoad(Drivable drivable) {
    bool ret = CityFlowPINVOKE.Router_isLastRoad(swigCPtr, Drivable.getCPtr(drivable));
    return ret;
  }

  public bool onLastRoad() {
    bool ret = CityFlowPINVOKE.Router_onLastRoad(swigCPtr);
    return ret;
  }

  public bool onValidLane() {
    bool ret = CityFlowPINVOKE.Router_onValidLane(swigCPtr);
    return ret;
  }

  public Lane getValidLane(Lane curLane) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Router_getValidLane(swigCPtr, Lane.getCPtr(curLane));
    Lane ret = (cPtr == global::System.IntPtr.Zero) ? null : new Lane(cPtr, false);
    return ret;
  }

  public void setVehicle(Vehicle vehicle) {
    CityFlowPINVOKE.Router_setVehicle(swigCPtr, Vehicle.getCPtr(vehicle));
  }

  public bool dijkstra(Road start, Road end, SWIGTYPE_p_std__vectorT_CityFlow__Road_p_t buffer) {
    bool ret = CityFlowPINVOKE.Router_dijkstra(swigCPtr, Road.getCPtr(start), Road.getCPtr(end), SWIGTYPE_p_std__vectorT_CityFlow__Road_p_t.getCPtr(buffer));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool updateShortestPath() {
    bool ret = CityFlowPINVOKE.Router_updateShortestPath(swigCPtr);
    return ret;
  }

  public bool setRoute(SWIGTYPE_p_std__vectorT_CityFlow__Road_p_t anchor) {
    bool ret = CityFlowPINVOKE.Router_setRoute(swigCPtr, SWIGTYPE_p_std__vectorT_CityFlow__Road_p_t.getCPtr(anchor));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_CityFlow__Road_p_t getFollowingRoads() {
    SWIGTYPE_p_std__vectorT_CityFlow__Road_p_t ret = new SWIGTYPE_p_std__vectorT_CityFlow__Road_p_t(CityFlowPINVOKE.Router_getFollowingRoads(swigCPtr), true);
    return ret;
  }

}

}
