//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class Segment : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Segment(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Segment obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Segment obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Segment() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_Segment(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Segment() : this(CityFlowPINVOKE.new_Segment__SWIG_0(), true) {
  }

  public Segment(uint index, Lane belongLane, double startPos, double endPos) : this(CityFlowPINVOKE.new_Segment__SWIG_1(index, Lane.getCPtr(belongLane), startPos, endPos), true) {
  }

  public double getStartPos() {
    double ret = CityFlowPINVOKE.Segment_getStartPos(swigCPtr);
    return ret;
  }

  public double getEndPos() {
    double ret = CityFlowPINVOKE.Segment_getEndPos(swigCPtr);
    return ret;
  }

  public uint getIndex() {
    uint ret = CityFlowPINVOKE.Segment_getIndex(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_std__listT_std__listT_CityFlow__Vehicle_p_t__iterator_t getVehicles() {
    SWIGTYPE_p_std__listT_std__listT_CityFlow__Vehicle_p_t__iterator_t ret = new SWIGTYPE_p_std__listT_std__listT_CityFlow__Vehicle_p_t__iterator_t(CityFlowPINVOKE.Segment_getVehicles__SWIG_0(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__listT_CityFlow__Vehicle_p_t__iterator findVehicle(Vehicle vehicle) {
    SWIGTYPE_p_std__listT_CityFlow__Vehicle_p_t__iterator ret = new SWIGTYPE_p_std__listT_CityFlow__Vehicle_p_t__iterator(CityFlowPINVOKE.Segment_findVehicle(swigCPtr, Vehicle.getCPtr(vehicle)), true);
    return ret;
  }

  public void removeVehicle(Vehicle vehicle) {
    CityFlowPINVOKE.Segment_removeVehicle(swigCPtr, Vehicle.getCPtr(vehicle));
  }

  public void insertVehicle(SWIGTYPE_p_std__listT_CityFlow__Vehicle_p_t__iterator vehicle) {
    CityFlowPINVOKE.Segment_insertVehicle(swigCPtr, SWIGTYPE_p_std__listT_CityFlow__Vehicle_p_t__iterator.getCPtr(vehicle));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
