//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class SimpleLaneChange : LaneChange {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal SimpleLaneChange(global::System.IntPtr cPtr, bool cMemoryOwn) : base(CityFlowPINVOKE.SimpleLaneChange_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SimpleLaneChange obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SimpleLaneChange obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_SimpleLaneChange(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public SimpleLaneChange(Vehicle vehicle) : this(CityFlowPINVOKE.new_SimpleLaneChange__SWIG_0(Vehicle.getCPtr(vehicle)), true) {
  }

  public SimpleLaneChange(Vehicle vehicle, LaneChange other) : this(CityFlowPINVOKE.new_SimpleLaneChange__SWIG_1(Vehicle.getCPtr(vehicle), LaneChange.getCPtr(other)), true) {
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void makeSignal(double interval) {
    CityFlowPINVOKE.SimpleLaneChange_makeSignal(swigCPtr, interval);
  }

  public override void sendSignal() {
    CityFlowPINVOKE.SimpleLaneChange_sendSignal(swigCPtr);
  }

  public override double yieldSpeed(double interval) {
    double ret = CityFlowPINVOKE.SimpleLaneChange_yieldSpeed(swigCPtr, interval);
    return ret;
  }

  public override double safeGapBefore() {
    double ret = CityFlowPINVOKE.SimpleLaneChange_safeGapBefore(swigCPtr);
    return ret;
  }

  public override double safeGapAfter() {
    double ret = CityFlowPINVOKE.SimpleLaneChange_safeGapAfter(swigCPtr);
    return ret;
  }

}

}
