//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class TrafficLight : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TrafficLight(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TrafficLight obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TrafficLight obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TrafficLight() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_TrafficLight(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public void init(int initPhaseIndex) {
    CityFlowPINVOKE.TrafficLight_init(swigCPtr, initPhaseIndex);
  }

  public int getCurrentPhaseIndex() {
    int ret = CityFlowPINVOKE.TrafficLight_getCurrentPhaseIndex(swigCPtr);
    return ret;
  }

  public LightPhase getCurrentPhase() {
    LightPhase ret = new LightPhase(CityFlowPINVOKE.TrafficLight_getCurrentPhase(swigCPtr), false);
    return ret;
  }

  public Intersection getIntersection() {
    Intersection ret = new Intersection(CityFlowPINVOKE.TrafficLight_getIntersection(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_CityFlow__LightPhase_t getPhases() {
    SWIGTYPE_p_std__vectorT_CityFlow__LightPhase_t ret = new SWIGTYPE_p_std__vectorT_CityFlow__LightPhase_t(CityFlowPINVOKE.TrafficLight_getPhases(swigCPtr), false);
    return ret;
  }

  public void passTime(double seconds) {
    CityFlowPINVOKE.TrafficLight_passTime(swigCPtr, seconds);
  }

  public void setPhase(int phaseIndex) {
    CityFlowPINVOKE.TrafficLight_setPhase(swigCPtr, phaseIndex);
  }

  public void reset() {
    CityFlowPINVOKE.TrafficLight_reset(swigCPtr);
  }

  public TrafficLight() : this(CityFlowPINVOKE.new_TrafficLight(), true) {
  }

}

}
