//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class Vehicle : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Vehicle(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Vehicle obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Vehicle obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Vehicle() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_Vehicle(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public bool isStraightHold {
    set {
      CityFlowPINVOKE.Vehicle_isStraightHold_set(swigCPtr, value);
    } 
    get {
      bool ret = CityFlowPINVOKE.Vehicle_isStraightHold_get(swigCPtr);
      return ret;
    } 
  }

  public Vehicle(Vehicle vehicle, Flow flow) : this(CityFlowPINVOKE.new_Vehicle__SWIG_0(Vehicle.getCPtr(vehicle), Flow.getCPtr(flow)), true) {
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vehicle(Vehicle vehicle) : this(CityFlowPINVOKE.new_Vehicle__SWIG_1(Vehicle.getCPtr(vehicle)), true) {
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vehicle(Vehicle vehicle, SWIGTYPE_p_std__string id, Engine engine, Flow flow) : this(CityFlowPINVOKE.new_Vehicle__SWIG_2(Vehicle.getCPtr(vehicle), SWIGTYPE_p_std__string.getCPtr(id), Engine.getCPtr(engine), Flow.getCPtr(flow)), true) {
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vehicle(Vehicle vehicle, SWIGTYPE_p_std__string id, Engine engine) : this(CityFlowPINVOKE.new_Vehicle__SWIG_3(Vehicle.getCPtr(vehicle), SWIGTYPE_p_std__string.getCPtr(id), Engine.getCPtr(engine)), true) {
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vehicle(VehicleInfo init, SWIGTYPE_p_std__string id, Engine engine, Flow flow) : this(CityFlowPINVOKE.new_Vehicle__SWIG_4(VehicleInfo.getCPtr(init), SWIGTYPE_p_std__string.getCPtr(id), Engine.getCPtr(engine), Flow.getCPtr(flow)), true) {
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vehicle(VehicleInfo init, SWIGTYPE_p_std__string id, Engine engine) : this(CityFlowPINVOKE.new_Vehicle__SWIG_5(VehicleInfo.getCPtr(init), SWIGTYPE_p_std__string.getCPtr(id), Engine.getCPtr(engine)), true) {
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setDeltaDistance(double dis) {
    CityFlowPINVOKE.Vehicle_setDeltaDistance(swigCPtr, dis);
  }

  public void setSpeed(double speed) {
    CityFlowPINVOKE.Vehicle_setSpeed(swigCPtr, speed);
  }

  public void setCustomSpeed(double speed) {
    CityFlowPINVOKE.Vehicle_setCustomSpeed(swigCPtr, speed);
  }

  public void setDis(double dis) {
    CityFlowPINVOKE.Vehicle_setDis(swigCPtr, dis);
  }

  public void setDrivable(Drivable drivable) {
    CityFlowPINVOKE.Vehicle_setDrivable(swigCPtr, Drivable.getCPtr(drivable));
  }

  public bool hasSetDrivable() {
    bool ret = CityFlowPINVOKE.Vehicle_hasSetDrivable(swigCPtr);
    return ret;
  }

  public bool hasSetSpeed() {
    bool ret = CityFlowPINVOKE.Vehicle_hasSetSpeed(swigCPtr);
    return ret;
  }

  public bool hasSetCustomSpeed() {
    bool ret = CityFlowPINVOKE.Vehicle_hasSetCustomSpeed(swigCPtr);
    return ret;
  }

  public double getBufferSpeed() {
    double ret = CityFlowPINVOKE.Vehicle_getBufferSpeed(swigCPtr);
    return ret;
  }

  public bool hasSetEnd() {
    bool ret = CityFlowPINVOKE.Vehicle_hasSetEnd(swigCPtr);
    return ret;
  }

  public void setEnd(bool end) {
    CityFlowPINVOKE.Vehicle_setEnd(swigCPtr, end);
  }

  public void unSetEnd() {
    CityFlowPINVOKE.Vehicle_unSetEnd(swigCPtr);
  }

  public void unSetDrivable() {
    CityFlowPINVOKE.Vehicle_unSetDrivable(swigCPtr);
  }

  public void setEnterLaneLinkTime(uint enterLaneLinkTime) {
    CityFlowPINVOKE.Vehicle_setEnterLaneLinkTime(swigCPtr, enterLaneLinkTime);
  }

  public void setBlocker(Vehicle blocker) {
    CityFlowPINVOKE.Vehicle_setBlocker(swigCPtr, Vehicle.getCPtr(blocker));
  }

  public double getBufferDis() {
    double ret = CityFlowPINVOKE.Vehicle_getBufferDis(swigCPtr);
    return ret;
  }

  public void update() {
    CityFlowPINVOKE.Vehicle_update(swigCPtr);
  }

  public void setPriority(int priority) {
    CityFlowPINVOKE.Vehicle_setPriority(swigCPtr, priority);
  }

  public SWIGTYPE_p_std__string getId() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(CityFlowPINVOKE.Vehicle_getId(swigCPtr), true);
    return ret;
  }

  public double getSpeed() {
    double ret = CityFlowPINVOKE.Vehicle_getSpeed(swigCPtr);
    return ret;
  }

  public double getLen() {
    double ret = CityFlowPINVOKE.Vehicle_getLen(swigCPtr);
    return ret;
  }

  public double getWidth() {
    double ret = CityFlowPINVOKE.Vehicle_getWidth(swigCPtr);
    return ret;
  }

  public double getDistance() {
    double ret = CityFlowPINVOKE.Vehicle_getDistance(swigCPtr);
    return ret;
  }

  public Point getPoint() {
    Point ret = new Point(CityFlowPINVOKE.Vehicle_getPoint(swigCPtr), true);
    return ret;
  }

  public double getMaxPosAcc() {
    double ret = CityFlowPINVOKE.Vehicle_getMaxPosAcc(swigCPtr);
    return ret;
  }

  public double getMaxNegAcc() {
    double ret = CityFlowPINVOKE.Vehicle_getMaxNegAcc(swigCPtr);
    return ret;
  }

  public double getUsualPosAcc() {
    double ret = CityFlowPINVOKE.Vehicle_getUsualPosAcc(swigCPtr);
    return ret;
  }

  public double getUsualNegAcc() {
    double ret = CityFlowPINVOKE.Vehicle_getUsualNegAcc(swigCPtr);
    return ret;
  }

  public double getMinGap() {
    double ret = CityFlowPINVOKE.Vehicle_getMinGap(swigCPtr);
    return ret;
  }

  public double getYieldDistance() {
    double ret = CityFlowPINVOKE.Vehicle_getYieldDistance(swigCPtr);
    return ret;
  }

  public double getTurnSpeed() {
    double ret = CityFlowPINVOKE.Vehicle_getTurnSpeed(swigCPtr);
    return ret;
  }

  public Vehicle getBlocker() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Vehicle_getBlocker(swigCPtr);
    Vehicle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vehicle(cPtr, false);
    return ret;
  }

  public Vehicle getBufferBlocker() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Vehicle_getBufferBlocker(swigCPtr);
    Vehicle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vehicle(cPtr, false);
    return ret;
  }

  public Drivable getCurDrivable() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Vehicle_getCurDrivable(swigCPtr);
    Drivable ret = (cPtr == global::System.IntPtr.Zero) ? null : new Drivable(cPtr, false);
    return ret;
  }

  public Lane getCurLane() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Vehicle_getCurLane(swigCPtr);
    Lane ret = (cPtr == global::System.IntPtr.Zero) ? null : new Lane(cPtr, false);
    return ret;
  }

  public Drivable getNextDrivable(int i) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Vehicle_getNextDrivable__SWIG_0(swigCPtr, i);
    Drivable ret = (cPtr == global::System.IntPtr.Zero) ? null : new Drivable(cPtr, false);
    return ret;
  }

  public Drivable getNextDrivable() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Vehicle_getNextDrivable__SWIG_1(swigCPtr);
    Drivable ret = (cPtr == global::System.IntPtr.Zero) ? null : new Drivable(cPtr, false);
    return ret;
  }

  public Drivable getPrevDrivable(int i) {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Vehicle_getPrevDrivable__SWIG_0(swigCPtr, i);
    Drivable ret = (cPtr == global::System.IntPtr.Zero) ? null : new Drivable(cPtr, false);
    return ret;
  }

  public Drivable getPrevDrivable() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Vehicle_getPrevDrivable__SWIG_1(swigCPtr);
    Drivable ret = (cPtr == global::System.IntPtr.Zero) ? null : new Drivable(cPtr, false);
    return ret;
  }

  public int getPriority() {
    int ret = CityFlowPINVOKE.Vehicle_getPriority(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_std__pairT_CityFlow__Point_CityFlow__Point_t getCurPos() {
    SWIGTYPE_p_std__pairT_CityFlow__Point_CityFlow__Point_t ret = new SWIGTYPE_p_std__pairT_CityFlow__Point_CityFlow__Point_t(CityFlowPINVOKE.Vehicle_getCurPos(swigCPtr), true);
    return ret;
  }

  public ControlInfo getNextSpeed(double interval) {
    ControlInfo ret = new ControlInfo(CityFlowPINVOKE.Vehicle_getNextSpeed(swigCPtr, interval), true);
    return ret;
  }

  public Drivable getChangedDrivable() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Vehicle_getChangedDrivable(swigCPtr);
    Drivable ret = (cPtr == global::System.IntPtr.Zero) ? null : new Drivable(cPtr, false);
    return ret;
  }

  public double getEnterTime() {
    double ret = CityFlowPINVOKE.Vehicle_getEnterTime(swigCPtr);
    return ret;
  }

  public bool isEnd() {
    bool ret = CityFlowPINVOKE.Vehicle_isEnd(swigCPtr);
    return ret;
  }

  public bool isIntersectionRelated() {
    bool ret = CityFlowPINVOKE.Vehicle_isIntersectionRelated(swigCPtr);
    return ret;
  }

  public double getBrakeDistanceAfterAccel(double acc, double dec, double interval) {
    double ret = CityFlowPINVOKE.Vehicle_getBrakeDistanceAfterAccel(swigCPtr, acc, dec, interval);
    return ret;
  }

  public double getMinBrakeDistance() {
    double ret = CityFlowPINVOKE.Vehicle_getMinBrakeDistance(swigCPtr);
    return ret;
  }

  public double getUsualBrakeDistance() {
    double ret = CityFlowPINVOKE.Vehicle_getUsualBrakeDistance(swigCPtr);
    return ret;
  }

  public double getNoCollisionSpeed(double vL, double dL, double vF, double dF, double gap, double interval, double targetGap) {
    double ret = CityFlowPINVOKE.Vehicle_getNoCollisionSpeed(swigCPtr, vL, dL, vF, dF, gap, interval, targetGap);
    return ret;
  }

  public double getCarFollowSpeed(double interval) {
    double ret = CityFlowPINVOKE.Vehicle_getCarFollowSpeed(swigCPtr, interval);
    return ret;
  }

  public double getStopBeforeSpeed(double distance, double interval) {
    double ret = CityFlowPINVOKE.Vehicle_getStopBeforeSpeed(swigCPtr, distance, interval);
    return ret;
  }

  public int getReachSteps(double distance, double targetSpeed, double acc) {
    int ret = CityFlowPINVOKE.Vehicle_getReachSteps(swigCPtr, distance, targetSpeed, acc);
    return ret;
  }

  public int getReachStepsOnLaneLink(double distance, LaneLink laneLink) {
    int ret = CityFlowPINVOKE.Vehicle_getReachStepsOnLaneLink(swigCPtr, distance, LaneLink.getCPtr(laneLink));
    return ret;
  }

  public double getDistanceUntilSpeed(double speed, double acc) {
    double ret = CityFlowPINVOKE.Vehicle_getDistanceUntilSpeed(swigCPtr, speed, acc);
    return ret;
  }

  public bool canYield(double dist) {
    bool ret = CityFlowPINVOKE.Vehicle_canYield(swigCPtr, dist);
    return ret;
  }

  public void updateLeaderAndGap(Vehicle leader) {
    CityFlowPINVOKE.Vehicle_updateLeaderAndGap(swigCPtr, Vehicle.getCPtr(leader));
  }

  public Vehicle getLeader() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Vehicle_getLeader(swigCPtr);
    Vehicle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vehicle(cPtr, false);
    return ret;
  }

  public double getEnterLaneLinkTime() {
    double ret = CityFlowPINVOKE.Vehicle_getEnterLaneLinkTime(swigCPtr);
    return ret;
  }

  public double getHeadwayTime() {
    double ret = CityFlowPINVOKE.Vehicle_getHeadwayTime(swigCPtr);
    return ret;
  }

  public double getMaxSpeed() {
    double ret = CityFlowPINVOKE.Vehicle_getMaxSpeed(swigCPtr);
    return ret;
  }

  public double getApproachingIntersectionDistance() {
    double ret = CityFlowPINVOKE.Vehicle_getApproachingIntersectionDistance(swigCPtr);
    return ret;
  }

  public double getIntersectionRelatedSpeed(double interval) {
    double ret = CityFlowPINVOKE.Vehicle_getIntersectionRelatedSpeed(swigCPtr, interval);
    return ret;
  }

  public bool isRunning() {
    bool ret = CityFlowPINVOKE.Vehicle_isRunning(swigCPtr);
    return ret;
  }

  public void setRunning(bool isRunning) {
    CityFlowPINVOKE.Vehicle_setRunning__SWIG_0(swigCPtr, isRunning);
  }

  public void setRunning() {
    CityFlowPINVOKE.Vehicle_setRunning__SWIG_1(swigCPtr);
  }

  public bool hasPartner() {
    bool ret = CityFlowPINVOKE.Vehicle_hasPartner(swigCPtr);
    return ret;
  }

  public bool isReal() {
    bool ret = CityFlowPINVOKE.Vehicle_isReal(swigCPtr);
    return ret;
  }

  public uint getSegmentIndex() {
    uint ret = CityFlowPINVOKE.Vehicle_getSegmentIndex(swigCPtr);
    return ret;
  }

  public void setSegmentIndex(int segmentIndex) {
    CityFlowPINVOKE.Vehicle_setSegmentIndex(swigCPtr, segmentIndex);
  }

  public void setShadow(Vehicle veh) {
    CityFlowPINVOKE.Vehicle_setShadow(swigCPtr, Vehicle.getCPtr(veh));
  }

  public void setParent(Vehicle veh) {
    CityFlowPINVOKE.Vehicle_setParent(swigCPtr, Vehicle.getCPtr(veh));
  }

  public void setLane(Lane nextLane) {
    CityFlowPINVOKE.Vehicle_setLane(swigCPtr, Lane.getCPtr(nextLane));
  }

  public void finishChanging() {
    CityFlowPINVOKE.Vehicle_finishChanging(swigCPtr);
  }

  public void setOffset(double offset) {
    CityFlowPINVOKE.Vehicle_setOffset(swigCPtr, offset);
  }

  public double getOffset() {
    double ret = CityFlowPINVOKE.Vehicle_getOffset(swigCPtr);
    return ret;
  }

  public Vehicle getPartner() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Vehicle_getPartner(swigCPtr);
    Vehicle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vehicle(cPtr, false);
    return ret;
  }

  public void setId(SWIGTYPE_p_std__string id) {
    CityFlowPINVOKE.Vehicle_setId(swigCPtr, SWIGTYPE_p_std__string.getCPtr(id));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
  }

  public void makeLaneChangeSignal(double interval) {
    CityFlowPINVOKE.Vehicle_makeLaneChangeSignal(swigCPtr, interval);
  }

  public bool planLaneChange() {
    bool ret = CityFlowPINVOKE.Vehicle_planLaneChange(swigCPtr);
    return ret;
  }

  public void receiveSignal(Vehicle sender) {
    CityFlowPINVOKE.Vehicle_receiveSignal(swigCPtr, Vehicle.getCPtr(sender));
  }

  public void sendSignal() {
    CityFlowPINVOKE.Vehicle_sendSignal(swigCPtr);
  }

  public void clearSignal() {
    CityFlowPINVOKE.Vehicle_clearSignal(swigCPtr);
  }

  public void updateLaneChangeNeighbor() {
    CityFlowPINVOKE.Vehicle_updateLaneChangeNeighbor(swigCPtr);
  }

  public SWIGTYPE_p_std__shared_ptrT_CityFlow__LaneChange_t getLaneChange() {
    SWIGTYPE_p_std__shared_ptrT_CityFlow__LaneChange_t ret = new SWIGTYPE_p_std__shared_ptrT_CityFlow__LaneChange_t(CityFlowPINVOKE.Vehicle_getLaneChange(swigCPtr), true);
    return ret;
  }

  public SWIGTYPE_p_std__listT_CityFlow__Vehicle_p_t__iterator getListIterator() {
    SWIGTYPE_p_std__listT_CityFlow__Vehicle_p_t__iterator ret = new SWIGTYPE_p_std__listT_CityFlow__Vehicle_p_t__iterator(CityFlowPINVOKE.Vehicle_getListIterator(swigCPtr), true);
    return ret;
  }

  public void insertShadow(Vehicle shadow) {
    CityFlowPINVOKE.Vehicle_insertShadow(swigCPtr, Vehicle.getCPtr(shadow));
  }

  public bool onValidLane() {
    bool ret = CityFlowPINVOKE.Vehicle_onValidLane(swigCPtr);
    return ret;
  }

  public Lane getValidLane() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Vehicle_getValidLane(swigCPtr);
    Lane ret = (cPtr == global::System.IntPtr.Zero) ? null : new Lane(cPtr, false);
    return ret;
  }

  public bool canChange() {
    bool ret = CityFlowPINVOKE.Vehicle_canChange(swigCPtr);
    return ret;
  }

  public double getGap() {
    double ret = CityFlowPINVOKE.Vehicle_getGap(swigCPtr);
    return ret;
  }

  public int laneChangeUrgency() {
    int ret = CityFlowPINVOKE.Vehicle_laneChangeUrgency(swigCPtr);
    return ret;
  }

  public Vehicle getTargetLeader() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Vehicle_getTargetLeader(swigCPtr);
    Vehicle ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vehicle(cPtr, false);
    return ret;
  }

  public int lastLaneChangeDirection() {
    int ret = CityFlowPINVOKE.Vehicle_lastLaneChangeDirection(swigCPtr);
    return ret;
  }

  public int getLaneChangeDirection() {
    int ret = CityFlowPINVOKE.Vehicle_getLaneChangeDirection(swigCPtr);
    return ret;
  }

  public bool isChanging() {
    bool ret = CityFlowPINVOKE.Vehicle_isChanging(swigCPtr);
    return ret;
  }

  public double getMaxOffset() {
    double ret = CityFlowPINVOKE.Vehicle_getMaxOffset(swigCPtr);
    return ret;
  }

  public void abortLaneChange() {
    CityFlowPINVOKE.Vehicle_abortLaneChange(swigCPtr);
  }

  public void updateRoute() {
    CityFlowPINVOKE.Vehicle_updateRoute(swigCPtr);
  }

  public Road getFirstRoad() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Vehicle_getFirstRoad(swigCPtr);
    Road ret = (cPtr == global::System.IntPtr.Zero) ? null : new Road(cPtr, false);
    return ret;
  }

  public void setFirstDrivable() {
    CityFlowPINVOKE.Vehicle_setFirstDrivable(swigCPtr);
  }

  public bool isRouteValid() {
    bool ret = CityFlowPINVOKE.Vehicle_isRouteValid(swigCPtr);
    return ret;
  }

  public Flow getFlow() {
    global::System.IntPtr cPtr = CityFlowPINVOKE.Vehicle_getFlow(swigCPtr);
    Flow ret = (cPtr == global::System.IntPtr.Zero) ? null : new Flow(cPtr, false);
    return ret;
  }

  public bool setRoute(SWIGTYPE_p_std__vectorT_CityFlow__Road_p_t anchor) {
    bool ret = CityFlowPINVOKE.Vehicle_setRoute(swigCPtr, SWIGTYPE_p_std__vectorT_CityFlow__Road_p_t.getCPtr(anchor));
    if (CityFlowPINVOKE.SWIGPendingException.Pending) throw CityFlowPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__mapT_std__string_std__string_t getInfo() {
    SWIGTYPE_p_std__mapT_std__string_std__string_t ret = new SWIGTYPE_p_std__mapT_std__string_std__string_t(CityFlowPINVOKE.Vehicle_getInfo(swigCPtr), true);
    return ret;
  }

}

}
