//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CityFlowCore {

public class VehicleInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VehicleInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VehicleInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VehicleInfo obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VehicleInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CityFlowPINVOKE.delete_VehicleInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double speed {
    set {
      CityFlowPINVOKE.VehicleInfo_speed_set(swigCPtr, value);
    } 
    get {
      double ret = CityFlowPINVOKE.VehicleInfo_speed_get(swigCPtr);
      return ret;
    } 
  }

  public double len {
    set {
      CityFlowPINVOKE.VehicleInfo_len_set(swigCPtr, value);
    } 
    get {
      double ret = CityFlowPINVOKE.VehicleInfo_len_get(swigCPtr);
      return ret;
    } 
  }

  public double width {
    set {
      CityFlowPINVOKE.VehicleInfo_width_set(swigCPtr, value);
    } 
    get {
      double ret = CityFlowPINVOKE.VehicleInfo_width_get(swigCPtr);
      return ret;
    } 
  }

  public double maxPosAcc {
    set {
      CityFlowPINVOKE.VehicleInfo_maxPosAcc_set(swigCPtr, value);
    } 
    get {
      double ret = CityFlowPINVOKE.VehicleInfo_maxPosAcc_get(swigCPtr);
      return ret;
    } 
  }

  public double maxNegAcc {
    set {
      CityFlowPINVOKE.VehicleInfo_maxNegAcc_set(swigCPtr, value);
    } 
    get {
      double ret = CityFlowPINVOKE.VehicleInfo_maxNegAcc_get(swigCPtr);
      return ret;
    } 
  }

  public double usualPosAcc {
    set {
      CityFlowPINVOKE.VehicleInfo_usualPosAcc_set(swigCPtr, value);
    } 
    get {
      double ret = CityFlowPINVOKE.VehicleInfo_usualPosAcc_get(swigCPtr);
      return ret;
    } 
  }

  public double usualNegAcc {
    set {
      CityFlowPINVOKE.VehicleInfo_usualNegAcc_set(swigCPtr, value);
    } 
    get {
      double ret = CityFlowPINVOKE.VehicleInfo_usualNegAcc_get(swigCPtr);
      return ret;
    } 
  }

  public double minGap {
    set {
      CityFlowPINVOKE.VehicleInfo_minGap_set(swigCPtr, value);
    } 
    get {
      double ret = CityFlowPINVOKE.VehicleInfo_minGap_get(swigCPtr);
      return ret;
    } 
  }

  public double maxSpeed {
    set {
      CityFlowPINVOKE.VehicleInfo_maxSpeed_set(swigCPtr, value);
    } 
    get {
      double ret = CityFlowPINVOKE.VehicleInfo_maxSpeed_get(swigCPtr);
      return ret;
    } 
  }

  public double headwayTime {
    set {
      CityFlowPINVOKE.VehicleInfo_headwayTime_set(swigCPtr, value);
    } 
    get {
      double ret = CityFlowPINVOKE.VehicleInfo_headwayTime_get(swigCPtr);
      return ret;
    } 
  }

  public double yieldDistance {
    set {
      CityFlowPINVOKE.VehicleInfo_yieldDistance_set(swigCPtr, value);
    } 
    get {
      double ret = CityFlowPINVOKE.VehicleInfo_yieldDistance_get(swigCPtr);
      return ret;
    } 
  }

  public double turnSpeed {
    set {
      CityFlowPINVOKE.VehicleInfo_turnSpeed_set(swigCPtr, value);
    } 
    get {
      double ret = CityFlowPINVOKE.VehicleInfo_turnSpeed_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_std__shared_ptrT_CityFlow__Route_const_t route {
    set {
      CityFlowPINVOKE.VehicleInfo_route_set(swigCPtr, SWIGTYPE_p_std__shared_ptrT_CityFlow__Route_const_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CityFlowPINVOKE.VehicleInfo_route_get(swigCPtr);
      SWIGTYPE_p_std__shared_ptrT_CityFlow__Route_const_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__shared_ptrT_CityFlow__Route_const_t(cPtr, false);
      return ret;
    } 
  }

  public VehicleInfo() : this(CityFlowPINVOKE.new_VehicleInfo(), true) {
  }

}

}
