<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>PREACT</RootNamespace>
    <BaseOutputPath>..\..\WUInity\Assets\PREACT\</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Source\Hazards\Dispersion\Modules\GaussianReleaseGPU - Copy\**" />
    <EmbeddedResource Remove="Source\Hazards\Dispersion\Modules\GaussianReleaseGPU - Copy\**" />
    <None Remove="Source\Hazards\Dispersion\Modules\GaussianReleaseGPU - Copy\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Source\Evacuation\Traffic\Modules\SUMO\Build_notes.txt" />
    <Content Include="Source\Evacuation\Traffic\Modules\SUMO\version_info.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GeoTimeZone" Version="6.1.0" />
    <PackageReference Include="ILGPU" Version="1.5.3" />
    <PackageReference Include="ILGPU.Algorithms" Version="1.5.3" />
    <PackageReference Include="Itinero" Version="1.5.1" />
    <PackageReference Include="Itinero.IO.Osm" Version="1.5.1" />
    <PackageReference Include="OsmSharp.IO.API" Version="1.0.5" />
    <PackageReference Include="SGP.NET" Version="1.4.0" />
    <PackageReference Include="System.Text.Json" Version="10.0.5" />
    <PackageReference Include="TimeZoneConverter" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="gdalconst_csharp">
      <HintPath>ThirdParty\GDAL\x64\gdalconst_csharp.dll</HintPath>
    </Reference>
    <Reference Include="gdal_csharp">
      <HintPath>ThirdParty\GDAL\x64\gdal_csharp.dll</HintPath>
    </Reference>
    <Reference Include="kPERILcore">
      <HintPath>..\..\..\kperil\kPERILcore\bin\Release\netstandard2.1\kPERILcore.dll</HintPath>
    </Reference>
    <Reference Include="ogr_csharp">
      <HintPath>ThirdParty\GDAL\x64\ogr_csharp.dll</HintPath>
    </Reference>
    <Reference Include="OpenMeteo">
      <HintPath>ThirdParty\Open-Meteo-DotNet\OpenMeteo.dll</HintPath>
    </Reference>
    <Reference Include="osr_csharp">
      <HintPath>ThirdParty\GDAL\x64\osr_csharp.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="Runtimes\Native\Behave\x64\Behave.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Runtimes\Native\CityFlow\x64\CityFlow.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Runtimes\Native\FOFEM\x64\FOFEM.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Runtimes\Native\GDAL\x64\gdalconst_wrap.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Runtimes\Native\GDAL\x64\gdal_wrap.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Runtimes\Native\GDAL\x64\libgdalconst_wrap.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Runtimes\Native\GDAL\x64\libgdal_wrap.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Runtimes\Native\GDAL\x64\libogr_wrap.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Runtimes\Native\GDAL\x64\libosr_wrap.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Runtimes\Native\GDAL\x64\ogr_wrap.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Runtimes\Native\GDAL\x64\osr_wrap.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Runtimes\Managed\kPERIL\kPERILcore.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Runtimes\Managed\Open-Meteo-DotNet\OpenMeteo.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Runtimes\Native\NFDRS4\x64\libNFDRS4core.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Runtimes\Native\NFDRS4\x64\NFDRS4core.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Source\Evacuation\Consequence\Dose\" />
    <Folder Include="Source\Evacuation\Consequence\Concentration\" />
    <Folder Include="Source\Hazards\Dispersion\Modules\GaussianReleaseGPU\" />
  </ItemGroup>

</Project>
