//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace FOFEMcore {

public class ConsumeDataInput : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ConsumeDataInput(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ConsumeDataInput obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ConsumeDataInput obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ConsumeDataInput() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          FOFEMPINVOKE.delete_ConsumeDataInput(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public float f_Duff {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_Duff_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_Duff_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DufDep {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_DufDep_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_DufDep_get(swigCPtr);
      return ret;
    } 
  }

  public float f_MoistDuff {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_MoistDuff_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_MoistDuff_get(swigCPtr);
      return ret;
    } 
  }

  public float f_MoistDW10 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_MoistDW10_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_MoistDW10_get(swigCPtr);
      return ret;
    } 
  }

  public float f_MoistDW1000 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_MoistDW1000_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_MoistDW1000_get(swigCPtr);
      return ret;
    } 
  }

  public float f_LitMoi {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_LitMoi_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_LitMoi_get(swigCPtr);
      return ret;
    } 
  }

  public float f_Lit {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_Lit_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_Lit_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DW1 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_DW1_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_DW1_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DW10 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_DW10_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_DW10_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DW100 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_DW100_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_DW100_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DW1000 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_DW1000_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_DW1000_get(swigCPtr);
      return ret;
    } 
  }

  public float f_pcRot {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_pcRot_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_pcRot_get(swigCPtr);
      return ret;
    } 
  }

  public string cr_WD {
    set {
      FOFEMPINVOKE.ConsumeDataInput_cr_WD_set(swigCPtr, value);
    } 
    get {
      string ret = FOFEMPINVOKE.ConsumeDataInput_cr_WD_get(swigCPtr);
      return ret;
    } 
  }

  public float f_Snd_DW3 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_Snd_DW3_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_Snd_DW3_get(swigCPtr);
      return ret;
    } 
  }

  public float f_Snd_DW6 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_Snd_DW6_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_Snd_DW6_get(swigCPtr);
      return ret;
    } 
  }

  public float f_Snd_DW9 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_Snd_DW9_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_Snd_DW9_get(swigCPtr);
      return ret;
    } 
  }

  public float f_Snd_DW20 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_Snd_DW20_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_Snd_DW20_get(swigCPtr);
      return ret;
    } 
  }

  public float f_Rot_DW3 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_Rot_DW3_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_Rot_DW3_get(swigCPtr);
      return ret;
    } 
  }

  public float f_Rot_DW6 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_Rot_DW6_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_Rot_DW6_get(swigCPtr);
      return ret;
    } 
  }

  public float f_Rot_DW9 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_Rot_DW9_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_Rot_DW9_get(swigCPtr);
      return ret;
    } 
  }

  public float f_Rot_DW20 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_Rot_DW20_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_Rot_DW20_get(swigCPtr);
      return ret;
    } 
  }

  public float f_CroFol {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_CroFol_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_CroFol_get(swigCPtr);
      return ret;
    } 
  }

  public float f_CroBra {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_CroBra_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_CroBra_get(swigCPtr);
      return ret;
    } 
  }

  public float f_Pc_CroBrn {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_Pc_CroBrn_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_Pc_CroBrn_get(swigCPtr);
      return ret;
    } 
  }

  public float f_Herb {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_Herb_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_Herb_get(swigCPtr);
      return ret;
    } 
  }

  public float f_Shrub {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_Shrub_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_Shrub_get(swigCPtr);
      return ret;
    } 
  }

  public float f_HSFCon {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_HSFCon_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_HSFCon_get(swigCPtr);
      return ret;
    } 
  }

  public float f_PerDufCon {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_PerDufCon_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_PerDufCon_get(swigCPtr);
      return ret;
    } 
  }

  public string cr_LoadFN {
    set {
      FOFEMPINVOKE.ConsumeDataInput_cr_LoadFN_set(swigCPtr, value);
    } 
    get {
      string ret = FOFEMPINVOKE.ConsumeDataInput_cr_LoadFN_get(swigCPtr);
      return ret;
    } 
  }

  public string cr_EmiFN {
    set {
      FOFEMPINVOKE.ConsumeDataInput_cr_EmiFN_set(swigCPtr, value);
    } 
    get {
      string ret = FOFEMPINVOKE.ConsumeDataInput_cr_EmiFN_get(swigCPtr);
      return ret;
    } 
  }

  public float f_SURat_Lit {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_SURat_Lit_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_SURat_Lit_get(swigCPtr);
      return ret;
    } 
  }

  public float f_SURat_DW1 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_SURat_DW1_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_SURat_DW1_get(swigCPtr);
      return ret;
    } 
  }

  public float f_SURat_DW10 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_SURat_DW10_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_SURat_DW10_get(swigCPtr);
      return ret;
    } 
  }

  public float f_SURat_DW100 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_SURat_DW100_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_SURat_DW100_get(swigCPtr);
      return ret;
    } 
  }

  public float f_SURat_DWk_3_6 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_SURat_DWk_3_6_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_SURat_DWk_3_6_get(swigCPtr);
      return ret;
    } 
  }

  public float f_SURat_DWk_6_9 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_SURat_DWk_6_9_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_SURat_DWk_6_9_get(swigCPtr);
      return ret;
    } 
  }

  public float f_SURat_DWk_9_20 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_SURat_DWk_9_20_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_SURat_DWk_9_20_get(swigCPtr);
      return ret;
    } 
  }

  public float f_SURat_DWk_20 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_SURat_DWk_20_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_SURat_DWk_20_get(swigCPtr);
      return ret;
    } 
  }

  public int l_MAX_TIMES {
    set {
      FOFEMPINVOKE.ConsumeDataInput_l_MAX_TIMES_set(swigCPtr, value);
    } 
    get {
      int ret = FOFEMPINVOKE.ConsumeDataInput_l_MAX_TIMES_get(swigCPtr);
      return ret;
    } 
  }

  public float f_INTENSITY {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_INTENSITY_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_INTENSITY_get(swigCPtr);
      return ret;
    } 
  }

  public float f_IG_TIME {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_IG_TIME_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_IG_TIME_get(swigCPtr);
      return ret;
    } 
  }

  public float f_WINDSPEED {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_WINDSPEED_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_WINDSPEED_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DEPTH {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_DEPTH_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_DEPTH_get(swigCPtr);
      return ret;
    } 
  }

  public float f_AMBIENT_TEMP {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_AMBIENT_TEMP_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_AMBIENT_TEMP_get(swigCPtr);
      return ret;
    } 
  }

  public float f_R0 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_R0_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_R0_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DR {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_DR_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_DR_get(swigCPtr);
      return ret;
    } 
  }

  public float f_TIMESTEP {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_TIMESTEP_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_TIMESTEP_get(swigCPtr);
      return ret;
    } 
  }

  public string cr_CoverGroup {
    set {
      FOFEMPINVOKE.ConsumeDataInput_cr_CoverGroup_set(swigCPtr, value);
    } 
    get {
      string ret = FOFEMPINVOKE.ConsumeDataInput_cr_CoverGroup_get(swigCPtr);
      return ret;
    } 
  }

  public string cr_CoverClass {
    set {
      FOFEMPINVOKE.ConsumeDataInput_cr_CoverClass_set(swigCPtr, value);
    } 
    get {
      string ret = FOFEMPINVOKE.ConsumeDataInput_cr_CoverClass_get(swigCPtr);
      return ret;
    } 
  }

  public string cr_Season {
    set {
      FOFEMPINVOKE.ConsumeDataInput_cr_Season_set(swigCPtr, value);
    } 
    get {
      string ret = FOFEMPINVOKE.ConsumeDataInput_cr_Season_get(swigCPtr);
      return ret;
    } 
  }

  public string cr_Region {
    set {
      FOFEMPINVOKE.ConsumeDataInput_cr_Region_set(swigCPtr, value);
    } 
    get {
      string ret = FOFEMPINVOKE.ConsumeDataInput_cr_Region_get(swigCPtr);
      return ret;
    } 
  }

  public string cr_FuelCategory {
    set {
      FOFEMPINVOKE.ConsumeDataInput_cr_FuelCategory_set(swigCPtr, value);
    } 
    get {
      string ret = FOFEMPINVOKE.ConsumeDataInput_cr_FuelCategory_get(swigCPtr);
      return ret;
    } 
  }

  public string cr_DufMoiMet {
    set {
      FOFEMPINVOKE.ConsumeDataInput_cr_DufMoiMet_set(swigCPtr, value);
    } 
    get {
      string ret = FOFEMPINVOKE.ConsumeDataInput_cr_DufMoiMet_get(swigCPtr);
      return ret;
    } 
  }

  public string cr_EmiFla {
    set {
      FOFEMPINVOKE.ConsumeDataInput_cr_EmiFla_set(swigCPtr, value);
    } 
    get {
      string ret = FOFEMPINVOKE.ConsumeDataInput_cr_EmiFla_get(swigCPtr);
      return ret;
    } 
  }

  public string cr_EmiSmo {
    set {
      FOFEMPINVOKE.ConsumeDataInput_cr_EmiSmo_set(swigCPtr, value);
    } 
    get {
      string ret = FOFEMPINVOKE.ConsumeDataInput_cr_EmiSmo_get(swigCPtr);
      return ret;
    } 
  }

  public string cr_EmiDuf {
    set {
      FOFEMPINVOKE.ConsumeDataInput_cr_EmiDuf_set(swigCPtr, value);
    } 
    get {
      string ret = FOFEMPINVOKE.ConsumeDataInput_cr_EmiDuf_get(swigCPtr);
      return ret;
    } 
  }

  public string cr_EmiFull {
    set {
      FOFEMPINVOKE.ConsumeDataInput_cr_EmiFull_set(swigCPtr, value);
    } 
    get {
      string ret = FOFEMPINVOKE.ConsumeDataInput_cr_EmiFull_get(swigCPtr);
      return ret;
    } 
  }

  public float f_CriInt {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_CriInt_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_CriInt_get(swigCPtr);
      return ret;
    } 
  }

  public float f_fCO {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_fCO_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_fCO_get(swigCPtr);
      return ret;
    } 
  }

  public float f_fCO2 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_fCO2_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_fCO2_get(swigCPtr);
      return ret;
    } 
  }

  public float f_fCH4 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_fCH4_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_fCH4_get(swigCPtr);
      return ret;
    } 
  }

  public float f_fPM25 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_fPM25_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_fPM25_get(swigCPtr);
      return ret;
    } 
  }

  public float f_fPM10 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_fPM10_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_fPM10_get(swigCPtr);
      return ret;
    } 
  }

  public float f_fNOX {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_fNOX_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_fNOX_get(swigCPtr);
      return ret;
    } 
  }

  public float f_fSO2 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_fSO2_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_fSO2_get(swigCPtr);
      return ret;
    } 
  }

  public float f_sCO {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_sCO_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_sCO_get(swigCPtr);
      return ret;
    } 
  }

  public float f_sCO2 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_sCO2_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_sCO2_get(swigCPtr);
      return ret;
    } 
  }

  public float f_sCH4 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_sCH4_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_sCH4_get(swigCPtr);
      return ret;
    } 
  }

  public float f_sPM25 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_sPM25_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_sPM25_get(swigCPtr);
      return ret;
    } 
  }

  public float f_sPM10 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_sPM10_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_sPM10_get(swigCPtr);
      return ret;
    } 
  }

  public float f_sNOX {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_sNOX_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_sNOX_get(swigCPtr);
      return ret;
    } 
  }

  public float f_sSO2 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_sSO2_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_sSO2_get(swigCPtr);
      return ret;
    } 
  }

  public float f_dCO {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_dCO_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_dCO_get(swigCPtr);
      return ret;
    } 
  }

  public float f_dCO2 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_dCO2_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_dCO2_get(swigCPtr);
      return ret;
    } 
  }

  public float f_dCH4 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_dCH4_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_dCH4_get(swigCPtr);
      return ret;
    } 
  }

  public float f_dPM25 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_dPM25_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_dPM25_get(swigCPtr);
      return ret;
    } 
  }

  public float f_dPM10 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_dPM10_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_dPM10_get(swigCPtr);
      return ret;
    } 
  }

  public float f_dNOX {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_dNOX_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_dNOX_get(swigCPtr);
      return ret;
    } 
  }

  public float f_dSO2 {
    set {
      FOFEMPINVOKE.ConsumeDataInput_f_dSO2_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataInput_f_dSO2_get(swigCPtr);
      return ret;
    } 
  }

  public string cr_BatchEqu {
    set {
      FOFEMPINVOKE.ConsumeDataInput_cr_BatchEqu_set(swigCPtr, value);
    } 
    get {
      string ret = FOFEMPINVOKE.ConsumeDataInput_cr_BatchEqu_get(swigCPtr);
      return ret;
    } 
  }

  public int i_EqLit {
    set {
      FOFEMPINVOKE.ConsumeDataInput_i_EqLit_set(swigCPtr, value);
    } 
    get {
      int ret = FOFEMPINVOKE.ConsumeDataInput_i_EqLit_get(swigCPtr);
      return ret;
    } 
  }

  public int i_EgDufLoa {
    set {
      FOFEMPINVOKE.ConsumeDataInput_i_EgDufLoa_set(swigCPtr, value);
    } 
    get {
      int ret = FOFEMPINVOKE.ConsumeDataInput_i_EgDufLoa_get(swigCPtr);
      return ret;
    } 
  }

  public int i_EqDufDep {
    set {
      FOFEMPINVOKE.ConsumeDataInput_i_EqDufDep_set(swigCPtr, value);
    } 
    get {
      int ret = FOFEMPINVOKE.ConsumeDataInput_i_EqDufDep_get(swigCPtr);
      return ret;
    } 
  }

  public int i_EqMSE {
    set {
      FOFEMPINVOKE.ConsumeDataInput_i_EqMSE_set(swigCPtr, value);
    } 
    get {
      int ret = FOFEMPINVOKE.ConsumeDataInput_i_EqMSE_get(swigCPtr);
      return ret;
    } 
  }

  public int i_EqHerb {
    set {
      FOFEMPINVOKE.ConsumeDataInput_i_EqHerb_set(swigCPtr, value);
    } 
    get {
      int ret = FOFEMPINVOKE.ConsumeDataInput_i_EqHerb_get(swigCPtr);
      return ret;
    } 
  }

  public int i_EqShrub {
    set {
      FOFEMPINVOKE.ConsumeDataInput_i_EqShrub_set(swigCPtr, value);
    } 
    get {
      int ret = FOFEMPINVOKE.ConsumeDataInput_i_EqShrub_get(swigCPtr);
      return ret;
    } 
  }

  public ConsumeDataInput() : this(FOFEMPINVOKE.new_ConsumeDataInput(), true) {
  }

}

}
