//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace FOFEMcore {

public class ConsumeDataOutput : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ConsumeDataOutput(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ConsumeDataOutput obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ConsumeDataOutput obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ConsumeDataOutput() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          FOFEMPINVOKE.delete_ConsumeDataOutput(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string cr_BrnIg {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_cr_BrnIg_set(swigCPtr, value);
    } 
    get {
      string ret = FOFEMPINVOKE.ConsumeDataOutput_cr_BrnIg_get(swigCPtr);
      return ret;
    } 
  }

  public int i_LitEqu {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_i_LitEqu_set(swigCPtr, value);
    } 
    get {
      int ret = FOFEMPINVOKE.ConsumeDataOutput_i_LitEqu_get(swigCPtr);
      return ret;
    } 
  }

  public float f_LitPre {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_LitPre_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_LitPre_get(swigCPtr);
      return ret;
    } 
  }

  public float f_LitCon {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_LitCon_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_LitCon_get(swigCPtr);
      return ret;
    } 
  }

  public float f_LitPos {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_LitPos_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_LitPos_get(swigCPtr);
      return ret;
    } 
  }

  public float f_LitPer {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_LitPer_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_LitPer_get(swigCPtr);
      return ret;
    } 
  }

  public int i_DW1Equ {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_i_DW1Equ_set(swigCPtr, value);
    } 
    get {
      int ret = FOFEMPINVOKE.ConsumeDataOutput_i_DW1Equ_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DW1Pre {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_DW1Pre_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_DW1Pre_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DW1Con {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_DW1Con_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_DW1Con_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DW1Pos {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_DW1Pos_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_DW1Pos_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DW1Per {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_DW1Per_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_DW1Per_get(swigCPtr);
      return ret;
    } 
  }

  public int i_DW10Equ {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_i_DW10Equ_set(swigCPtr, value);
    } 
    get {
      int ret = FOFEMPINVOKE.ConsumeDataOutput_i_DW10Equ_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DW10Pre {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_DW10Pre_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_DW10Pre_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DW10Con {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_DW10Con_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_DW10Con_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DW10Pos {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_DW10Pos_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_DW10Pos_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DW10Per {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_DW10Per_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_DW10Per_get(swigCPtr);
      return ret;
    } 
  }

  public int i_DW100Equ {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_i_DW100Equ_set(swigCPtr, value);
    } 
    get {
      int ret = FOFEMPINVOKE.ConsumeDataOutput_i_DW100Equ_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DW100Pre {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_DW100Pre_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_DW100Pre_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DW100Con {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_DW100Con_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_DW100Con_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DW100Pos {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_DW100Pos_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_DW100Pos_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DW100Per {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_DW100Per_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_DW100Per_get(swigCPtr);
      return ret;
    } 
  }

  public int i_Snd_DW1kEqu {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_i_Snd_DW1kEqu_set(swigCPtr, value);
    } 
    get {
      int ret = FOFEMPINVOKE.ConsumeDataOutput_i_Snd_DW1kEqu_get(swigCPtr);
      return ret;
    } 
  }

  public float f_Snd_DW1kPre {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_Snd_DW1kPre_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_Snd_DW1kPre_get(swigCPtr);
      return ret;
    } 
  }

  public float f_Snd_DW1kCon {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_Snd_DW1kCon_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_Snd_DW1kCon_get(swigCPtr);
      return ret;
    } 
  }

  public float f_Snd_DW1kPos {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_Snd_DW1kPos_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_Snd_DW1kPos_get(swigCPtr);
      return ret;
    } 
  }

  public float f_Snd_DW1kPer {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_Snd_DW1kPer_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_Snd_DW1kPer_get(swigCPtr);
      return ret;
    } 
  }

  public int i_Rot_DW1kEqu {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_i_Rot_DW1kEqu_set(swigCPtr, value);
    } 
    get {
      int ret = FOFEMPINVOKE.ConsumeDataOutput_i_Rot_DW1kEqu_get(swigCPtr);
      return ret;
    } 
  }

  public float f_Rot_DW1kPre {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_Rot_DW1kPre_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_Rot_DW1kPre_get(swigCPtr);
      return ret;
    } 
  }

  public float f_Rot_DW1kCon {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_Rot_DW1kCon_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_Rot_DW1kCon_get(swigCPtr);
      return ret;
    } 
  }

  public float f_Rot_DW1kPos {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_Rot_DW1kPos_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_Rot_DW1kPos_get(swigCPtr);
      return ret;
    } 
  }

  public float f_Rot_DW1kPer {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_Rot_DW1kPer_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_Rot_DW1kPer_get(swigCPtr);
      return ret;
    } 
  }

  public int i_DufEqu {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_i_DufEqu_set(swigCPtr, value);
    } 
    get {
      int ret = FOFEMPINVOKE.ConsumeDataOutput_i_DufEqu_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DufPre {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_DufPre_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_DufPre_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DufCon {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_DufCon_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_DufCon_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DufPos {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_DufPos_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_DufPos_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DufPer {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_DufPer_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_DufPer_get(swigCPtr);
      return ret;
    } 
  }

  public int i_DufDepEqu {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_i_DufDepEqu_set(swigCPtr, value);
    } 
    get {
      int ret = FOFEMPINVOKE.ConsumeDataOutput_i_DufDepEqu_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DufDepPre {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_DufDepPre_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_DufDepPre_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DufDepCon {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_DufDepCon_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_DufDepCon_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DufDepPos {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_DufDepPos_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_DufDepPos_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DufDepPer {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_DufDepPer_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_DufDepPer_get(swigCPtr);
      return ret;
    } 
  }

  public float f_MSEPer {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_MSEPer_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_MSEPer_get(swigCPtr);
      return ret;
    } 
  }

  public int i_MSEEqu {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_i_MSEEqu_set(swigCPtr, value);
    } 
    get {
      int ret = FOFEMPINVOKE.ConsumeDataOutput_i_MSEEqu_get(swigCPtr);
      return ret;
    } 
  }

  public int i_HerEqu {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_i_HerEqu_set(swigCPtr, value);
    } 
    get {
      int ret = FOFEMPINVOKE.ConsumeDataOutput_i_HerEqu_get(swigCPtr);
      return ret;
    } 
  }

  public float f_HerPre {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_HerPre_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_HerPre_get(swigCPtr);
      return ret;
    } 
  }

  public float f_HerCon {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_HerCon_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_HerCon_get(swigCPtr);
      return ret;
    } 
  }

  public float f_HerPos {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_HerPos_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_HerPos_get(swigCPtr);
      return ret;
    } 
  }

  public float f_HerPer {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_HerPer_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_HerPer_get(swigCPtr);
      return ret;
    } 
  }

  public int i_ShrEqu {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_i_ShrEqu_set(swigCPtr, value);
    } 
    get {
      int ret = FOFEMPINVOKE.ConsumeDataOutput_i_ShrEqu_get(swigCPtr);
      return ret;
    } 
  }

  public float f_ShrPre {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_ShrPre_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_ShrPre_get(swigCPtr);
      return ret;
    } 
  }

  public float f_ShrCon {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_ShrCon_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_ShrCon_get(swigCPtr);
      return ret;
    } 
  }

  public float f_ShrPos {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_ShrPos_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_ShrPos_get(swigCPtr);
      return ret;
    } 
  }

  public float f_ShrPer {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_ShrPer_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_ShrPer_get(swigCPtr);
      return ret;
    } 
  }

  public int i_FolEqu {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_i_FolEqu_set(swigCPtr, value);
    } 
    get {
      int ret = FOFEMPINVOKE.ConsumeDataOutput_i_FolEqu_get(swigCPtr);
      return ret;
    } 
  }

  public float f_FolPre {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_FolPre_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_FolPre_get(swigCPtr);
      return ret;
    } 
  }

  public float f_FolCon {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_FolCon_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_FolCon_get(swigCPtr);
      return ret;
    } 
  }

  public float f_FolPos {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_FolPos_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_FolPos_get(swigCPtr);
      return ret;
    } 
  }

  public float f_FolPer {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_FolPer_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_FolPer_get(swigCPtr);
      return ret;
    } 
  }

  public int i_BraEqu {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_i_BraEqu_set(swigCPtr, value);
    } 
    get {
      int ret = FOFEMPINVOKE.ConsumeDataOutput_i_BraEqu_get(swigCPtr);
      return ret;
    } 
  }

  public float f_BraPre {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_BraPre_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_BraPre_get(swigCPtr);
      return ret;
    } 
  }

  public float f_BraCon {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_BraCon_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_BraCon_get(swigCPtr);
      return ret;
    } 
  }

  public float f_BraPos {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_BraPos_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_BraPos_get(swigCPtr);
      return ret;
    } 
  }

  public float f_BraPer {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_BraPer_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_BraPer_get(swigCPtr);
      return ret;
    } 
  }

  public float f_TotPre {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_TotPre_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_TotPre_get(swigCPtr);
      return ret;
    } 
  }

  public float f_TotCon {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_TotCon_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_TotCon_get(swigCPtr);
      return ret;
    } 
  }

  public float f_TotPos {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_TotPos_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_TotPos_get(swigCPtr);
      return ret;
    } 
  }

  public float f_TotPer {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_TotPer_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_TotPer_get(swigCPtr);
      return ret;
    } 
  }

  public float f_S3Pos {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_S3Pos_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_S3Pos_get(swigCPtr);
      return ret;
    } 
  }

  public float f_S3Con {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_S3Con_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_S3Con_get(swigCPtr);
      return ret;
    } 
  }

  public float f_S3Pre {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_S3Pre_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_S3Pre_get(swigCPtr);
      return ret;
    } 
  }

  public float f_S3Per {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_S3Per_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_S3Per_get(swigCPtr);
      return ret;
    } 
  }

  public float f_S6Pos {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_S6Pos_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_S6Pos_get(swigCPtr);
      return ret;
    } 
  }

  public float f_S6Con {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_S6Con_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_S6Con_get(swigCPtr);
      return ret;
    } 
  }

  public float f_S6Pre {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_S6Pre_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_S6Pre_get(swigCPtr);
      return ret;
    } 
  }

  public float f_S6Per {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_S6Per_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_S6Per_get(swigCPtr);
      return ret;
    } 
  }

  public float f_S9Pos {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_S9Pos_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_S9Pos_get(swigCPtr);
      return ret;
    } 
  }

  public float f_S9Con {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_S9Con_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_S9Con_get(swigCPtr);
      return ret;
    } 
  }

  public float f_S9Pre {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_S9Pre_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_S9Pre_get(swigCPtr);
      return ret;
    } 
  }

  public float f_S9Per {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_S9Per_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_S9Per_get(swigCPtr);
      return ret;
    } 
  }

  public float f_S20Pos {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_S20Pos_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_S20Pos_get(swigCPtr);
      return ret;
    } 
  }

  public float f_S20Con {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_S20Con_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_S20Con_get(swigCPtr);
      return ret;
    } 
  }

  public float f_S20Pre {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_S20Pre_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_S20Pre_get(swigCPtr);
      return ret;
    } 
  }

  public float f_S20Per {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_S20Per_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_S20Per_get(swigCPtr);
      return ret;
    } 
  }

  public float f_R3Pos {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_R3Pos_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_R3Pos_get(swigCPtr);
      return ret;
    } 
  }

  public float f_R3Con {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_R3Con_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_R3Con_get(swigCPtr);
      return ret;
    } 
  }

  public float f_R3Pre {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_R3Pre_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_R3Pre_get(swigCPtr);
      return ret;
    } 
  }

  public float f_R3Per {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_R3Per_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_R3Per_get(swigCPtr);
      return ret;
    } 
  }

  public float f_R6Pos {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_R6Pos_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_R6Pos_get(swigCPtr);
      return ret;
    } 
  }

  public float f_R6Con {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_R6Con_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_R6Con_get(swigCPtr);
      return ret;
    } 
  }

  public float f_R6Pre {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_R6Pre_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_R6Pre_get(swigCPtr);
      return ret;
    } 
  }

  public float f_R6Per {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_R6Per_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_R6Per_get(swigCPtr);
      return ret;
    } 
  }

  public float f_R9Pos {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_R9Pos_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_R9Pos_get(swigCPtr);
      return ret;
    } 
  }

  public float f_R9Con {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_R9Con_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_R9Con_get(swigCPtr);
      return ret;
    } 
  }

  public float f_R9Pre {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_R9Pre_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_R9Pre_get(swigCPtr);
      return ret;
    } 
  }

  public float f_R9Per {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_R9Per_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_R9Per_get(swigCPtr);
      return ret;
    } 
  }

  public float f_R20Pos {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_R20Pos_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_R20Pos_get(swigCPtr);
      return ret;
    } 
  }

  public float f_R20Con {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_R20Con_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_R20Con_get(swigCPtr);
      return ret;
    } 
  }

  public float f_R20Pre {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_R20Pre_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_R20Pre_get(swigCPtr);
      return ret;
    } 
  }

  public float f_R20Per {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_R20Per_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_R20Per_get(swigCPtr);
      return ret;
    } 
  }

  public float f_PM10F {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_PM10F_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_PM10F_get(swigCPtr);
      return ret;
    } 
  }

  public float f_PM25F {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_PM25F_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_PM25F_get(swigCPtr);
      return ret;
    } 
  }

  public float f_CH4F {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_CH4F_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_CH4F_get(swigCPtr);
      return ret;
    } 
  }

  public float f_COF {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_COF_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_COF_get(swigCPtr);
      return ret;
    } 
  }

  public float f_CO2F {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_CO2F_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_CO2F_get(swigCPtr);
      return ret;
    } 
  }

  public float f_NOXF {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_NOXF_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_NOXF_get(swigCPtr);
      return ret;
    } 
  }

  public float f_SO2F {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_SO2F_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_SO2F_get(swigCPtr);
      return ret;
    } 
  }

  public float f_PM10S {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_PM10S_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_PM10S_get(swigCPtr);
      return ret;
    } 
  }

  public float f_PM25S {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_PM25S_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_PM25S_get(swigCPtr);
      return ret;
    } 
  }

  public float f_CH4S {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_CH4S_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_CH4S_get(swigCPtr);
      return ret;
    } 
  }

  public float f_COS {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_COS_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_COS_get(swigCPtr);
      return ret;
    } 
  }

  public float f_CO2S {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_CO2S_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_CO2S_get(swigCPtr);
      return ret;
    } 
  }

  public float f_NOXS {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_NOXS_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_NOXS_get(swigCPtr);
      return ret;
    } 
  }

  public float f_SO2S {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_SO2S_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_SO2S_get(swigCPtr);
      return ret;
    } 
  }

  public float f_PM10S_Duff {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_PM10S_Duff_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_PM10S_Duff_get(swigCPtr);
      return ret;
    } 
  }

  public float f_PM25S_Duff {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_PM25S_Duff_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_PM25S_Duff_get(swigCPtr);
      return ret;
    } 
  }

  public float f_CH4S_Duff {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_CH4S_Duff_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_CH4S_Duff_get(swigCPtr);
      return ret;
    } 
  }

  public float f_COS_Duff {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_COS_Duff_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_COS_Duff_get(swigCPtr);
      return ret;
    } 
  }

  public float f_CO2S_Duff {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_CO2S_Duff_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_CO2S_Duff_get(swigCPtr);
      return ret;
    } 
  }

  public float f_NOXS_Duff {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_NOXS_Duff_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_NOXS_Duff_get(swigCPtr);
      return ret;
    } 
  }

  public float f_SO2S_Duff {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_SO2S_Duff_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_SO2S_Duff_get(swigCPtr);
      return ret;
    } 
  }

  public float f_FlaDur {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_FlaDur_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_FlaDur_get(swigCPtr);
      return ret;
    } 
  }

  public float f_SmoDur {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_SmoDur_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_SmoDur_get(swigCPtr);
      return ret;
    } 
  }

  public float f_FlaCon {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_FlaCon_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_FlaCon_get(swigCPtr);
      return ret;
    } 
  }

  public float f_SmoCon {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_f_SmoCon_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.ConsumeDataOutput_f_SmoCon_get(swigCPtr);
      return ret;
    } 
  }

  public double d_pm10f {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_d_pm10f_set(swigCPtr, value);
    } 
    get {
      double ret = FOFEMPINVOKE.ConsumeDataOutput_d_pm10f_get(swigCPtr);
      return ret;
    } 
  }

  public double d_pm10s {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_d_pm10s_set(swigCPtr, value);
    } 
    get {
      double ret = FOFEMPINVOKE.ConsumeDataOutput_d_pm10s_get(swigCPtr);
      return ret;
    } 
  }

  public double d_pm25f {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_d_pm25f_set(swigCPtr, value);
    } 
    get {
      double ret = FOFEMPINVOKE.ConsumeDataOutput_d_pm25f_get(swigCPtr);
      return ret;
    } 
  }

  public double d_pm25s {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_d_pm25s_set(swigCPtr, value);
    } 
    get {
      double ret = FOFEMPINVOKE.ConsumeDataOutput_d_pm25s_get(swigCPtr);
      return ret;
    } 
  }

  public double d_ch4f {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_d_ch4f_set(swigCPtr, value);
    } 
    get {
      double ret = FOFEMPINVOKE.ConsumeDataOutput_d_ch4f_get(swigCPtr);
      return ret;
    } 
  }

  public double d_ch4s {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_d_ch4s_set(swigCPtr, value);
    } 
    get {
      double ret = FOFEMPINVOKE.ConsumeDataOutput_d_ch4s_get(swigCPtr);
      return ret;
    } 
  }

  public double d_cof {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_d_cof_set(swigCPtr, value);
    } 
    get {
      double ret = FOFEMPINVOKE.ConsumeDataOutput_d_cof_get(swigCPtr);
      return ret;
    } 
  }

  public double d_cos {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_d_cos_set(swigCPtr, value);
    } 
    get {
      double ret = FOFEMPINVOKE.ConsumeDataOutput_d_cos_get(swigCPtr);
      return ret;
    } 
  }

  public double d_co2f {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_d_co2f_set(swigCPtr, value);
    } 
    get {
      double ret = FOFEMPINVOKE.ConsumeDataOutput_d_co2f_get(swigCPtr);
      return ret;
    } 
  }

  public double d_co2s {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_d_co2s_set(swigCPtr, value);
    } 
    get {
      double ret = FOFEMPINVOKE.ConsumeDataOutput_d_co2s_get(swigCPtr);
      return ret;
    } 
  }

  public double d_noxf {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_d_noxf_set(swigCPtr, value);
    } 
    get {
      double ret = FOFEMPINVOKE.ConsumeDataOutput_d_noxf_get(swigCPtr);
      return ret;
    } 
  }

  public double d_noxs {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_d_noxs_set(swigCPtr, value);
    } 
    get {
      double ret = FOFEMPINVOKE.ConsumeDataOutput_d_noxs_get(swigCPtr);
      return ret;
    } 
  }

  public double d_so2f {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_d_so2f_set(swigCPtr, value);
    } 
    get {
      double ret = FOFEMPINVOKE.ConsumeDataOutput_d_so2f_get(swigCPtr);
      return ret;
    } 
  }

  public double d_so2s {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_d_so2s_set(swigCPtr, value);
    } 
    get {
      double ret = FOFEMPINVOKE.ConsumeDataOutput_d_so2s_get(swigCPtr);
      return ret;
    } 
  }

  public d_SGV sr_SGV {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_sr_SGV_set(swigCPtr, d_SGV.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = FOFEMPINVOKE.ConsumeDataOutput_sr_SGV_get(swigCPtr);
      d_SGV ret = (cPtr == global::System.IntPtr.Zero) ? null : new d_SGV(cPtr, false);
      return ret;
    } 
  }

  public int iC_SGV {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_iC_SGV_set(swigCPtr, value);
    } 
    get {
      int ret = FOFEMPINVOKE.ConsumeDataOutput_iC_SGV_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_float fr_SFI {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_fr_SFI_set(swigCPtr, SWIGTYPE_p_float.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = FOFEMPINVOKE.ConsumeDataOutput_fr_SFI_get(swigCPtr);
      SWIGTYPE_p_float ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_float(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_float fr_SFIhs {
    set {
      FOFEMPINVOKE.ConsumeDataOutput_fr_SFIhs_set(swigCPtr, SWIGTYPE_p_float.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = FOFEMPINVOKE.ConsumeDataOutput_fr_SFIhs_get(swigCPtr);
      SWIGTYPE_p_float ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_float(cPtr, false);
      return ret;
    } 
  }

  public ConsumeDataOutput() : this(FOFEMPINVOKE.new_ConsumeDataOutput(), true) {
  }

}

}
