//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace FOFEMcore {

public class d_SGV : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal d_SGV(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(d_SGV obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(d_SGV obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~d_SGV() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          FOFEMPINVOKE.delete_d_SGV(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public float f_Sec {
    set {
      FOFEMPINVOKE.d_SGV_f_Sec_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_Sec_get(swigCPtr);
      return ret;
    } 
  }

  public float f_Amt {
    set {
      FOFEMPINVOKE.d_SGV_f_Amt_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_Amt_get(swigCPtr);
      return ret;
    } 
  }

  public float f_PM2_5 {
    set {
      FOFEMPINVOKE.d_SGV_f_PM2_5_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_PM2_5_get(swigCPtr);
      return ret;
    } 
  }

  public float f_PM10 {
    set {
      FOFEMPINVOKE.d_SGV_f_PM10_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_PM10_get(swigCPtr);
      return ret;
    } 
  }

  public float f_CH4 {
    set {
      FOFEMPINVOKE.d_SGV_f_CH4_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_CH4_get(swigCPtr);
      return ret;
    } 
  }

  public float f_CO2 {
    set {
      FOFEMPINVOKE.d_SGV_f_CO2_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_CO2_get(swigCPtr);
      return ret;
    } 
  }

  public float f_CO {
    set {
      FOFEMPINVOKE.d_SGV_f_CO_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_CO_get(swigCPtr);
      return ret;
    } 
  }

  public float f_NOX {
    set {
      FOFEMPINVOKE.d_SGV_f_NOX_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_NOX_get(swigCPtr);
      return ret;
    } 
  }

  public float f_SO2 {
    set {
      FOFEMPINVOKE.d_SGV_f_SO2_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_SO2_get(swigCPtr);
      return ret;
    } 
  }

  public float f_Inten {
    set {
      FOFEMPINVOKE.d_SGV_f_Inten_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_Inten_get(swigCPtr);
      return ret;
    } 
  }

  public float f_FlaCon {
    set {
      FOFEMPINVOKE.d_SGV_f_FlaCon_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_FlaCon_get(swigCPtr);
      return ret;
    } 
  }

  public float f_SmoCon {
    set {
      FOFEMPINVOKE.d_SGV_f_SmoCon_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_SmoCon_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DuffCon {
    set {
      FOFEMPINVOKE.d_SGV_f_DuffCon_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_DuffCon_get(swigCPtr);
      return ret;
    } 
  }

  public float f_HSFBCon {
    set {
      FOFEMPINVOKE.d_SGV_f_HSFBCon_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_HSFBCon_get(swigCPtr);
      return ret;
    } 
  }

  public float f_rm_Lit {
    set {
      FOFEMPINVOKE.d_SGV_f_rm_Lit_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_rm_Lit_get(swigCPtr);
      return ret;
    } 
  }

  public float f_rm_1Hr {
    set {
      FOFEMPINVOKE.d_SGV_f_rm_1Hr_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_rm_1Hr_get(swigCPtr);
      return ret;
    } 
  }

  public float f_rm_10Hr {
    set {
      FOFEMPINVOKE.d_SGV_f_rm_10Hr_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_rm_10Hr_get(swigCPtr);
      return ret;
    } 
  }

  public float f_rm_100Hr {
    set {
      FOFEMPINVOKE.d_SGV_f_rm_100Hr_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_rm_100Hr_get(swigCPtr);
      return ret;
    } 
  }

  public float f_rm_1kHr {
    set {
      FOFEMPINVOKE.d_SGV_f_rm_1kHr_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_rm_1kHr_get(swigCPtr);
      return ret;
    } 
  }

  public float f_cn_Lit {
    set {
      FOFEMPINVOKE.d_SGV_f_cn_Lit_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_cn_Lit_get(swigCPtr);
      return ret;
    } 
  }

  public float f_cn_1Hr {
    set {
      FOFEMPINVOKE.d_SGV_f_cn_1Hr_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_cn_1Hr_get(swigCPtr);
      return ret;
    } 
  }

  public float f_cn_10Hr {
    set {
      FOFEMPINVOKE.d_SGV_f_cn_10Hr_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_cn_10Hr_get(swigCPtr);
      return ret;
    } 
  }

  public float f_cn_100Hr {
    set {
      FOFEMPINVOKE.d_SGV_f_cn_100Hr_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_cn_100Hr_get(swigCPtr);
      return ret;
    } 
  }

  public float f_cn_1kHr {
    set {
      FOFEMPINVOKE.d_SGV_f_cn_1kHr_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_cn_1kHr_get(swigCPtr);
      return ret;
    } 
  }

  public float f_cn_1kHrFla {
    set {
      FOFEMPINVOKE.d_SGV_f_cn_1kHrFla_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_cn_1kHrFla_get(swigCPtr);
      return ret;
    } 
  }

  public float f_cn_1kHrSmo {
    set {
      FOFEMPINVOKE.d_SGV_f_cn_1kHrSmo_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_cn_1kHrSmo_get(swigCPtr);
      return ret;
    } 
  }

  public float f_pcSmo {
    set {
      FOFEMPINVOKE.d_SGV_f_pcSmo_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_pcSmo_get(swigCPtr);
      return ret;
    } 
  }

  public float f_cn_LitSmoPerCent {
    set {
      FOFEMPINVOKE.d_SGV_f_cn_LitSmoPerCent_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_cn_LitSmoPerCent_get(swigCPtr);
      return ret;
    } 
  }

  public float f_cn_1HrSmoPerCent {
    set {
      FOFEMPINVOKE.d_SGV_f_cn_1HrSmoPerCent_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_cn_1HrSmoPerCent_get(swigCPtr);
      return ret;
    } 
  }

  public float f_cn_10HrSmoPerCent {
    set {
      FOFEMPINVOKE.d_SGV_f_cn_10HrSmoPerCent_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_cn_10HrSmoPerCent_get(swigCPtr);
      return ret;
    } 
  }

  public float f_cn_100HrSmoPerCent {
    set {
      FOFEMPINVOKE.d_SGV_f_cn_100HrSmoPerCent_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_cn_100HrSmoPerCent_get(swigCPtr);
      return ret;
    } 
  }

  public float f_cn_1kSmoPerCent {
    set {
      FOFEMPINVOKE.d_SGV_f_cn_1kSmoPerCent_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.d_SGV_f_cn_1kSmoPerCent_get(swigCPtr);
      return ret;
    } 
  }

  public d_SGV() : this(FOFEMPINVOKE.new_d_SGV(), true) {
  }

}

}
