//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace FOFEMcore {

public class FOFEM {
  public static SWIGTYPE_p_int new_intArray(uint nelements) {
    global::System.IntPtr cPtr = FOFEMPINVOKE.new_intArray(nelements);
    SWIGTYPE_p_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_int(cPtr, false);
    return ret;
  }

  public static void delete_intArray(SWIGTYPE_p_int ary) {
    FOFEMPINVOKE.delete_intArray(SWIGTYPE_p_int.getCPtr(ary));
  }

  public static int intArray_getitem(SWIGTYPE_p_int ary, uint index) {
    int ret = FOFEMPINVOKE.intArray_getitem(SWIGTYPE_p_int.getCPtr(ary), index);
    return ret;
  }

  public static void intArray_setitem(SWIGTYPE_p_int ary, uint index, int value) {
    FOFEMPINVOKE.intArray_setitem(SWIGTYPE_p_int.getCPtr(ary), index, value);
  }

  public static SWIGTYPE_p_float new_floatArray(uint nelements) {
    global::System.IntPtr cPtr = FOFEMPINVOKE.new_floatArray(nelements);
    SWIGTYPE_p_float ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_float(cPtr, false);
    return ret;
  }

  public static void delete_floatArray(SWIGTYPE_p_float ary) {
    FOFEMPINVOKE.delete_floatArray(SWIGTYPE_p_float.getCPtr(ary));
  }

  public static float floatArray_getitem(SWIGTYPE_p_float ary, uint index) {
    float ret = FOFEMPINVOKE.floatArray_getitem(SWIGTYPE_p_float.getCPtr(ary), index);
    return ret;
  }

  public static void floatArray_setitem(SWIGTYPE_p_float ary, uint index, float value) {
    FOFEMPINVOKE.floatArray_setitem(SWIGTYPE_p_float.getCPtr(ary), index, value);
  }

  public static void CI_Init(ConsumeDataInput a_CI) {
    FOFEMPINVOKE.CI_Init(ConsumeDataInput.getCPtr(a_CI));
  }

  public static int CI_isSpring(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isSpring(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isFall(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isFall(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isWinter(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isWinter(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isSummer(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isSummer(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isSeason(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isSeason(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isShrubGroup(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isShrubGroup(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isShrubGroupChaparral(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isShrubGroupChaparral(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isGrassGroup(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isGrassGroup(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isSageBrush(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isSageBrush(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isPocosin(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isPocosin(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isPonderosa(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isPonderosa(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isWhiPinHem(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isWhiPinHem(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isRedJacPin(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isRedJacPin(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isBalBRWSpr(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isBalBRWSpr(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isCoastPlain(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isCoastPlain(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isPinFlaWoo(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isPinFlaWoo(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isCoverGroup(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isCoverGroup(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isSouthEast(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isSouthEast(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isInteriorWest(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isInteriorWest(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isPacificWest(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isPacificWest(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isNorthEast(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isNorthEast(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isNatural(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isNatural(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isPiles(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isPiles(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isSlash(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isSlash(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isDufEntire(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isDufEntire(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isDufLower(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isDufLower(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isDufNFDR(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isDufNFDR(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isDufAdjNFDR(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isDufAdjNFDR(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isDufMethod(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isDufMethod(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_isDuffWet(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_isDuffWet(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static void CI_Display(ConsumeDataInput a_CI) {
    FOFEMPINVOKE.CI_Display(ConsumeDataInput.getCPtr(a_CI));
  }

  public static float CI_MaxLoad(ConsumeDataInput a_CI) {
    float ret = FOFEMPINVOKE.CI_MaxLoad(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static int CI_OnlyDuff(ConsumeDataInput a_CI) {
    int ret = FOFEMPINVOKE.CI_OnlyDuff(ConsumeDataInput.getCPtr(a_CI));
    return ret;
  }

  public static void CO_Init(ConsumeDataOutput a_CO) {
    FOFEMPINVOKE.CO_Init(ConsumeDataOutput.getCPtr(a_CO));
  }

  public static SWIGTYPE_p_FILE SI_fopen(string cr_FN, string cr) {
    global::System.IntPtr cPtr = FOFEMPINVOKE.SI_fopen(cr_FN, cr);
    SWIGTYPE_p_FILE ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FILE(cPtr, false);
    return ret;
  }

  public static void SI_fprintfVal(SWIGTYPE_p_FILE fh, string cr_Fmt, float r_time) {
    FOFEMPINVOKE.SI_fprintfVal(SWIGTYPE_p_FILE.getCPtr(fh), cr_Fmt, r_time);
  }

  public static void SI_fprintfRet(SWIGTYPE_p_FILE fh, string cr_Ret) {
    FOFEMPINVOKE.SI_fprintfRet(SWIGTYPE_p_FILE.getCPtr(fh), cr_Ret);
  }

  public static void SI_fclose(SWIGTYPE_p_FILE fh) {
    FOFEMPINVOKE.SI_fclose(SWIGTYPE_p_FILE.getCPtr(fh));
  }

  public static void SI_Init(SoilDataInput a_SI) {
    FOFEMPINVOKE.SI_Init(SoilDataInput.getCPtr(a_SI));
  }

  public static void SO_Init(SoilDataOutput a_SO) {
    FOFEMPINVOKE.SO_Init(SoilDataOutput.getCPtr(a_SO));
  }

  public static int SH_Mngr(SoilDataInput a_SI, SoilDataOutput a_SO, SWIGTYPE_p_float fr_FI, SWIGTYPE_p_float fr_FIhs, string cr_TmpPth, string cr_ErrMes) {
    int ret = FOFEMPINVOKE.SH_Mngr(SoilDataInput.getCPtr(a_SI), SoilDataOutput.getCPtr(a_SO), SWIGTYPE_p_float.getCPtr(fr_FI), SWIGTYPE_p_float.getCPtr(fr_FIhs), cr_TmpPth, cr_ErrMes);
    return ret;
  }

  public static int NES_Read(string cr_Path, string cr_ErrMes) {
    int ret = FOFEMPINVOKE.NES_Read(cr_Path, cr_ErrMes);
    return ret;
  }

  public static int NES_Get_Factor(string cr_GrpNum, int ix, string cr_CovTyp, SWIGTYPE_p_float af_Factor, string cr_Name, string cr_Code) {
    int ret = FOFEMPINVOKE.NES_Get_Factor(cr_GrpNum, ix, cr_CovTyp, SWIGTYPE_p_float.getCPtr(af_Factor), cr_Name, cr_Code);
    return ret;
  }

  public static void NCT_Display() {
    FOFEMPINVOKE.NCT_Display();
  }

  public static void NES_Display() {
    FOFEMPINVOKE.NES_Display();
  }

  public static int NES_GetGrpCov(int ix, string cr_GrpNum, string cr_CovTyp, SWIGTYPE_p_int aiS_Def) {
    int ret = FOFEMPINVOKE.NES_GetGrpCov(ix, cr_GrpNum, cr_CovTyp, SWIGTYPE_p_int.getCPtr(aiS_Def));
    return ret;
  }

  public static int NES_Get_MajFactor(string cr_GrpNum, SWIGTYPE_p_float CO, SWIGTYPE_p_float CO2, SWIGTYPE_p_float CH4, SWIGTYPE_p_float PM25, SWIGTYPE_p_float PM10, SWIGTYPE_p_float NOX, SWIGTYPE_p_float SO2) {
    int ret = FOFEMPINVOKE.NES_Get_MajFactor(cr_GrpNum, SWIGTYPE_p_float.getCPtr(CO), SWIGTYPE_p_float.getCPtr(CO2), SWIGTYPE_p_float.getCPtr(CH4), SWIGTYPE_p_float.getCPtr(PM25), SWIGTYPE_p_float.getCPtr(PM10), SWIGTYPE_p_float.getCPtr(NOX), SWIGTYPE_p_float.getCPtr(SO2));
    return ret;
  }

  public static float NES_Get_CriFirInt() {
    float ret = FOFEMPINVOKE.NES_Get_CriFirInt();
    return ret;
  }

  public static float GramSqMt_To_Pounds(float f_Gram) {
    float ret = FOFEMPINVOKE.GramSqMt_To_Pounds(f_Gram);
    return ret;
  }

  public static int SGV_Init() {
    int ret = FOFEMPINVOKE.SGV_Init();
    return ret;
  }

  public static int SGV_GetTimPPA(int iX, SWIGTYPE_p_float af_Time, SWIGTYPE_p_float af_Amt) {
    int ret = FOFEMPINVOKE.SGV_GetTimPPA(iX, SWIGTYPE_p_float.getCPtr(af_Time), SWIGTYPE_p_float.getCPtr(af_Amt));
    return ret;
  }

  public static int SGV_Set(d_SGV a_SGV) {
    int ret = FOFEMPINVOKE.SGV_Set(d_SGV.getCPtr(a_SGV));
    return ret;
  }

  public static float SGV_Prepare(string cr_Name, SWIGTYPE_p_float af_MaxTim, SWIGTYPE_p_float af_MaxAmt) {
    float ret = FOFEMPINVOKE.SGV_Prepare(cr_Name, SWIGTYPE_p_float.getCPtr(af_MaxTim), SWIGTYPE_p_float.getCPtr(af_MaxAmt));
    return ret;
  }

  public static int SGV_Get(int iX, d_SGV a_SGV) {
    int ret = FOFEMPINVOKE.SGV_Get(iX, d_SGV.getCPtr(a_SGV));
    return ret;
  }

  public static float SGV_BurnOutTime(string cr_Cmp) {
    float ret = FOFEMPINVOKE.SGV_BurnOutTime(cr_Cmp);
    return ret;
  }

  public static float _Con(d_SGV a, string cr_Cmp, SWIGTYPE_p_float af_SmoPercent) {
    float ret = FOFEMPINVOKE._Con(d_SGV.getCPtr(a), cr_Cmp, SWIGTYPE_p_float.getCPtr(af_SmoPercent));
    return ret;
  }

  public static int SGV_GetFS(string cr_Cmp, SWIGTYPE_p_float af_Fla, SWIGTYPE_p_float af_Smo) {
    int ret = FOFEMPINVOKE.SGV_GetFS(cr_Cmp, SWIGTYPE_p_float.getCPtr(af_Fla), SWIGTYPE_p_float.getCPtr(af_Smo));
    return ret;
  }

  public static int SGV_FlaSmoDuf(d_SGV a, SWIGTYPE_p_float af_Fla, SWIGTYPE_p_float af_Smo, SWIGTYPE_p_float af_Duf) {
    int ret = FOFEMPINVOKE.SGV_FlaSmoDuf(d_SGV.getCPtr(a), SWIGTYPE_p_float.getCPtr(af_Fla), SWIGTYPE_p_float.getCPtr(af_Smo), SWIGTYPE_p_float.getCPtr(af_Duf));
    return ret;
  }

  public static int ConsumeManager(ConsumeDataInput a_CI, ConsumeDataOutput a_CO, string cr_ErrMes) {
    int ret = FOFEMPINVOKE.ConsumeManager(ConsumeDataInput.getCPtr(a_CI), ConsumeDataOutput.getCPtr(a_CO), cr_ErrMes);
    return ret;
  }

  public static readonly double e_DufMin = FOFEMPINVOKE.e_DufMin_get();
  public static readonly double e_DufMax = FOFEMPINVOKE.e_DufMax_get();
  public static readonly double e_DufDepMin = FOFEMPINVOKE.e_DufDepMin_get();
  public static readonly double e_DufDepMax = FOFEMPINVOKE.e_DufDepMax_get();
  public static readonly double e_MoiDW10Min = FOFEMPINVOKE.e_MoiDW10Min_get();
  public static readonly double e_MoiDW10Max = FOFEMPINVOKE.e_MoiDW10Max_get();
  public static readonly double e_LitMoiMin = FOFEMPINVOKE.e_LitMoiMin_get();
  public static readonly double e_LitMoiMax = FOFEMPINVOKE.e_LitMoiMax_get();
  public static readonly int eC_WD = FOFEMPINVOKE.eC_WD_get();
  public static readonly string e_GrassGroup = FOFEMPINVOKE.e_GrassGroup_get();
  public static readonly string e_SageBrush = FOFEMPINVOKE.e_SageBrush_get();
  public static readonly string e_ShrubGroup = FOFEMPINVOKE.e_ShrubGroup_get();
  public static readonly string e_ShrubGroupChaparral = FOFEMPINVOKE.e_ShrubGroupChaparral_get();
  public static readonly string e_Pocosin = FOFEMPINVOKE.e_Pocosin_get();
  public static readonly string e_Ponderosa = FOFEMPINVOKE.e_Ponderosa_get();
  public static readonly string e_WhiPinHem = FOFEMPINVOKE.e_WhiPinHem_get();
  public static readonly string e_RedJacPin = FOFEMPINVOKE.e_RedJacPin_get();
  public static readonly string e_BalBRWSpr = FOFEMPINVOKE.e_BalBRWSpr_get();
  public static readonly string e_PinFlaWoo = FOFEMPINVOKE.e_PinFlaWoo_get();
  public static readonly string e_CoastPlain = FOFEMPINVOKE.e_CoastPlain_get();
  public static readonly string e_CVT_GrassGroup = FOFEMPINVOKE.e_CVT_GrassGroup_get();
  public static readonly string e_CVT_SageBrush = FOFEMPINVOKE.e_CVT_SageBrush_get();
  public static readonly string e_CVT_ShrubGroup = FOFEMPINVOKE.e_CVT_ShrubGroup_get();
  public static readonly string e_CVT_ShrubGroupChaparral = FOFEMPINVOKE.e_CVT_ShrubGroupChaparral_get();
  public static readonly string e_CVT_Pocosin = FOFEMPINVOKE.e_CVT_Pocosin_get();
  public static readonly string e_CVT_Ponderosa = FOFEMPINVOKE.e_CVT_Ponderosa_get();
  public static readonly string e_CVT_WhiPinHem = FOFEMPINVOKE.e_CVT_WhiPinHem_get();
  public static readonly string e_CVT_RedJacPin = FOFEMPINVOKE.e_CVT_RedJacPin_get();
  public static readonly string e_CVT_BalBRWSpr = FOFEMPINVOKE.e_CVT_BalBRWSpr_get();
  public static readonly string e_CVT_PinFlaWoo = FOFEMPINVOKE.e_CVT_PinFlaWoo_get();
  public static readonly string e_CVT_CoastPlain = FOFEMPINVOKE.e_CVT_CoastPlain_get();
  public static readonly string GRASSGROUP = FOFEMPINVOKE.GRASSGROUP_get();
  public static readonly string SAGEBRUSH = FOFEMPINVOKE.SAGEBRUSH_get();
  public static readonly string SHRUBGROUP = FOFEMPINVOKE.SHRUBGROUP_get();
  public static readonly string POCOSIN = FOFEMPINVOKE.POCOSIN_get();
  public static readonly string PONDEROSA = FOFEMPINVOKE.PONDEROSA_get();
  public static readonly string WHIPINHEM = FOFEMPINVOKE.WHIPINHEM_get();
  public static readonly string REDJACPIN = FOFEMPINVOKE.REDJACPIN_get();
  public static readonly string BALBRWSPR = FOFEMPINVOKE.BALBRWSPR_get();
  public static readonly string PINFLAWOO = FOFEMPINVOKE.PINFLAWOO_get();
  public static readonly string COASTPLAIN = FOFEMPINVOKE.COASTPLAIN_get();
  public static readonly int eC_CoverGroup = FOFEMPINVOKE.eC_CoverGroup_get();
  public static readonly string e_CI_SAF = FOFEMPINVOKE.e_CI_SAF_get();
  public static readonly string e_CI_NVCS = FOFEMPINVOKE.e_CI_NVCS_get();
  public static readonly string e_CI_FCC = FOFEMPINVOKE.e_CI_FCC_get();
  public static readonly string e_CI_FLM = FOFEMPINVOKE.e_CI_FLM_get();
  public static readonly string e_CI_DefaultCoverClass = FOFEMPINVOKE.e_CI_DefaultCoverClass_get();
  public static readonly string e_Winter = FOFEMPINVOKE.e_Winter_get();
  public static readonly string e_Spring = FOFEMPINVOKE.e_Spring_get();
  public static readonly string e_Summer = FOFEMPINVOKE.e_Summer_get();
  public static readonly string e_Fall = FOFEMPINVOKE.e_Fall_get();
  public static readonly string WINTER = FOFEMPINVOKE.WINTER_get();
  public static readonly string SPRING = FOFEMPINVOKE.SPRING_get();
  public static readonly string SUMMER = FOFEMPINVOKE.SUMMER_get();
  public static readonly string FALL = FOFEMPINVOKE.FALL_get();
  public static readonly string e_SeasonDefault = FOFEMPINVOKE.e_SeasonDefault_get();
  public static readonly int eC_Season = FOFEMPINVOKE.eC_Season_get();
  public static readonly string e_CI_SouthEast = FOFEMPINVOKE.e_CI_SouthEast_get();
  public static readonly string e_CI_InteriorWest = FOFEMPINVOKE.e_CI_InteriorWest_get();
  public static readonly string e_CI_PacificWest = FOFEMPINVOKE.e_CI_PacificWest_get();
  public static readonly string e_CI_NorthEast = FOFEMPINVOKE.e_CI_NorthEast_get();
  public static readonly string SOUTHEAST = FOFEMPINVOKE.SOUTHEAST_get();
  public static readonly string INTERIORWEST = FOFEMPINVOKE.INTERIORWEST_get();
  public static readonly string PACIFICWEST = FOFEMPINVOKE.PACIFICWEST_get();
  public static readonly string NORTHEAST = FOFEMPINVOKE.NORTHEAST_get();
  public static readonly int eC_Region = FOFEMPINVOKE.eC_Region_get();
  public static readonly string e_Natural = FOFEMPINVOKE.e_Natural_get();
  public static readonly string e_Piles = FOFEMPINVOKE.e_Piles_get();
  public static readonly string e_Slash = FOFEMPINVOKE.e_Slash_get();
  public static readonly string NATURAL = FOFEMPINVOKE.NATURAL_get();
  public static readonly string PILES = FOFEMPINVOKE.PILES_get();
  public static readonly string SLASH = FOFEMPINVOKE.SLASH_get();
  public static readonly string e_FuelCategoryDefault = FOFEMPINVOKE.e_FuelCategoryDefault_get();
  public static readonly int eC_FuelCategory = FOFEMPINVOKE.eC_FuelCategory_get();
  public static readonly string e_Entire = FOFEMPINVOKE.e_Entire_get();
  public static readonly string e_Lower = FOFEMPINVOKE.e_Lower_get();
  public static readonly string e_NFDR = FOFEMPINVOKE.e_NFDR_get();
  public static readonly string e_Adj_NFDR = FOFEMPINVOKE.e_Adj_NFDR_get();
  public static readonly string ENTIRE = FOFEMPINVOKE.ENTIRE_get();
  public static readonly string LOWER = FOFEMPINVOKE.LOWER_get();
  public static readonly string NFDR = FOFEMPINVOKE.NFDR_get();
  public static readonly string ADJ_NFDR = FOFEMPINVOKE.ADJ_NFDR_get();
  public static readonly string e_DufMoiMetDefault = FOFEMPINVOKE.e_DufMoiMetDefault_get();
  public static readonly int eC_DufMoiMet = FOFEMPINVOKE.eC_DufMoiMet_get();
  public static readonly int e_EqMissing = FOFEMPINVOKE.e_EqMissing_get();
  public static readonly int e_EqDefault = FOFEMPINVOKE.e_EqDefault_get();
  public static readonly int eC_sfi = FOFEMPINVOKE.eC_sfi_get();
  public static readonly string e_SoiSimFail = FOFEMPINVOKE.e_SoiSimFail_get();
  public static readonly string e_SoilErr = FOFEMPINVOKE.e_SoilErr_get();
  public static readonly string e_FrameSFN = FOFEMPINVOKE.e_FrameSFN_get();
  public static readonly string e_FrameSstart = FOFEMPINVOKE.e_FrameSstart_get();
  public static readonly string e_FrameSend = FOFEMPINVOKE.e_FrameSend_get();
  public static readonly int e_Max1 = FOFEMPINVOKE.e_Max1_get();
  public static readonly int e_Max2 = FOFEMPINVOKE.e_Max2_get();
  public static readonly int e_mplus1 = FOFEMPINVOKE.e_mplus1_get();
  public static readonly int e_Layers = FOFEMPINVOKE.e_Layers_get();
  public static readonly string e_LoaSke = FOFEMPINVOKE.e_LoaSke_get();
  public static readonly string e_FinSil = FOFEMPINVOKE.e_FinSil_get();
  public static readonly string e_Fin = FOFEMPINVOKE.e_Fin_get();
  public static readonly string e_CoaSil = FOFEMPINVOKE.e_CoaSil_get();
  public static readonly string e_CoaLoa = FOFEMPINVOKE.e_CoaLoa_get();
  public static readonly string LOAMY_SKELETAL = FOFEMPINVOKE.LOAMY_SKELETAL_get();
  public static readonly string FINE_SILT = FOFEMPINVOKE.FINE_SILT_get();
  public static readonly string FINE = FOFEMPINVOKE.FINE_get();
  public static readonly string COARSE_SILT = FOFEMPINVOKE.COARSE_SILT_get();
  public static readonly string COARSE_LOAMY = FOFEMPINVOKE.COARSE_LOAMY_get();
  public static readonly int eC_SoilType = FOFEMPINVOKE.eC_SoilType_get();
  public static readonly string e_VeryDry = FOFEMPINVOKE.e_VeryDry_get();
  public static readonly string e_Dry = FOFEMPINVOKE.e_Dry_get();
  public static readonly string e_Moderate = FOFEMPINVOKE.e_Moderate_get();
  public static readonly string e_Wet = FOFEMPINVOKE.e_Wet_get();
  public static readonly string VERY_DRY = FOFEMPINVOKE.VERY_DRY_get();
  public static readonly string DRY = FOFEMPINVOKE.DRY_get();
  public static readonly string MODERATE = FOFEMPINVOKE.MODERATE_get();
  public static readonly string WET = FOFEMPINVOKE.WET_get();
  public static readonly int eC_MoistCond = FOFEMPINVOKE.eC_MoistCond_get();
  public static readonly int e_LayNone = FOFEMPINVOKE.e_LayNone_get();
  public static readonly string e_SM_Duff = FOFEMPINVOKE.e_SM_Duff_get();
  public static readonly string e_SM_ZDuff = FOFEMPINVOKE.e_SM_ZDuff_get();
  public static readonly double e_CriInt = FOFEMPINVOKE.e_CriInt_get();
  public static readonly string e_EmiFN = FOFEMPINVOKE.e_EmiFN_get();
  public static readonly string e_DefFlaGrp = FOFEMPINVOKE.e_DefFlaGrp_get();
  public static readonly string e_DefDufGrp = FOFEMPINVOKE.e_DefDufGrp_get();
  public static readonly string e_DefSmoGrp = FOFEMPINVOKE.e_DefSmoGrp_get();
  public static readonly int eC_SGV = FOFEMPINVOKE.eC_SGV_get();
  public static readonly string e_SGV_PM2_5 = FOFEMPINVOKE.e_SGV_PM2_5_get();
  public static readonly string e_SGV_PM10 = FOFEMPINVOKE.e_SGV_PM10_get();
  public static readonly string e_SGV_CH4 = FOFEMPINVOKE.e_SGV_CH4_get();
  public static readonly string e_SGV_CO2 = FOFEMPINVOKE.e_SGV_CO2_get();
  public static readonly string e_SGV_CO = FOFEMPINVOKE.e_SGV_CO_get();
  public static readonly string e_SGV_NOX = FOFEMPINVOKE.e_SGV_NOX_get();
  public static readonly string e_SGV_SO2 = FOFEMPINVOKE.e_SGV_SO2_get();
  public static readonly string e_SGV_Inten = FOFEMPINVOKE.e_SGV_Inten_get();
}

}
