//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace FOFEMcore {

public class SoilDataInput : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SoilDataInput(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SoilDataInput obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SoilDataInput obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~SoilDataInput() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          FOFEMPINVOKE.delete_SoilDataInput(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public float f_DufLoaPre {
    set {
      FOFEMPINVOKE.SoilDataInput_f_DufLoaPre_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.SoilDataInput_f_DufLoaPre_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DufConPer {
    set {
      FOFEMPINVOKE.SoilDataInput_f_DufConPer_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.SoilDataInput_f_DufConPer_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DufMoi {
    set {
      FOFEMPINVOKE.SoilDataInput_f_DufMoi_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.SoilDataInput_f_DufMoi_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DufDepPre {
    set {
      FOFEMPINVOKE.SoilDataInput_f_DufDepPre_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.SoilDataInput_f_DufDepPre_get(swigCPtr);
      return ret;
    } 
  }

  public float f_DufDepPos {
    set {
      FOFEMPINVOKE.SoilDataInput_f_DufDepPos_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.SoilDataInput_f_DufDepPos_get(swigCPtr);
      return ret;
    } 
  }

  public float f_SoilMoist {
    set {
      FOFEMPINVOKE.SoilDataInput_f_SoilMoist_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.SoilDataInput_f_SoilMoist_get(swigCPtr);
      return ret;
    } 
  }

  public string cr_BrnIg {
    set {
      FOFEMPINVOKE.SoilDataInput_cr_BrnIg_set(swigCPtr, value);
    } 
    get {
      string ret = FOFEMPINVOKE.SoilDataInput_cr_BrnIg_get(swigCPtr);
      return ret;
    } 
  }

  public string cr_SoilType {
    set {
      FOFEMPINVOKE.SoilDataInput_cr_SoilType_set(swigCPtr, value);
    } 
    get {
      string ret = FOFEMPINVOKE.SoilDataInput_cr_SoilType_get(swigCPtr);
      return ret;
    } 
  }

  public string cr_MoistCond {
    set {
      FOFEMPINVOKE.SoilDataInput_cr_MoistCond_set(swigCPtr, value);
    } 
    get {
      string ret = FOFEMPINVOKE.SoilDataInput_cr_MoistCond_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_float ar_FI {
    set {
      FOFEMPINVOKE.SoilDataInput_ar_FI_set(swigCPtr, SWIGTYPE_p_float.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = FOFEMPINVOKE.SoilDataInput_ar_FI_get(swigCPtr);
      SWIGTYPE_p_float ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_float(cPtr, false);
      return ret;
    } 
  }

  public float f_SoilWlEff {
    set {
      FOFEMPINVOKE.SoilDataInput_f_SoilWlEff_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.SoilDataInput_f_SoilWlEff_get(swigCPtr);
      return ret;
    } 
  }

  public float f_SoilHsEff {
    set {
      FOFEMPINVOKE.SoilDataInput_f_SoilHsEff_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.SoilDataInput_f_SoilHsEff_get(swigCPtr);
      return ret;
    } 
  }

  public float f_SoilDuffEff {
    set {
      FOFEMPINVOKE.SoilDataInput_f_SoilDuffEff_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.SoilDataInput_f_SoilDuffEff_get(swigCPtr);
      return ret;
    } 
  }

  public SoilDataInput() : this(FOFEMPINVOKE.new_SoilDataInput(), true) {
  }

}

}
