//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace FOFEMcore {

public class SoilDataOutput : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SoilDataOutput(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SoilDataOutput obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SoilDataOutput obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~SoilDataOutput() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          FOFEMPINVOKE.delete_SoilDataOutput(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SWIGTYPE_p_int ir_Temp {
    set {
      FOFEMPINVOKE.SoilDataOutput_ir_Temp_set(swigCPtr, SWIGTYPE_p_int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = FOFEMPINVOKE.SoilDataOutput_ir_Temp_get(swigCPtr);
      SWIGTYPE_p_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_int(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_int ir_TimSec {
    set {
      FOFEMPINVOKE.SoilDataOutput_ir_TimSec_set(swigCPtr, SWIGTYPE_p_int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = FOFEMPINVOKE.SoilDataOutput_ir_TimSec_get(swigCPtr);
      SWIGTYPE_p_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_int(cPtr, false);
      return ret;
    } 
  }

  public float f_cDufPre {
    set {
      FOFEMPINVOKE.SoilDataOutput_f_cDufPre_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.SoilDataOutput_f_cDufPre_get(swigCPtr);
      return ret;
    } 
  }

  public float f_cDufPost {
    set {
      FOFEMPINVOKE.SoilDataOutput_f_cDufPost_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.SoilDataOutput_f_cDufPost_get(swigCPtr);
      return ret;
    } 
  }

  public float f_Heatpc {
    set {
      FOFEMPINVOKE.SoilDataOutput_f_Heatpc_set(swigCPtr, value);
    } 
    get {
      float ret = FOFEMPINVOKE.SoilDataOutput_f_Heatpc_get(swigCPtr);
      return ret;
    } 
  }

  public int i_LayMaxDeg1 {
    set {
      FOFEMPINVOKE.SoilDataOutput_i_LayMaxDeg1_set(swigCPtr, value);
    } 
    get {
      int ret = FOFEMPINVOKE.SoilDataOutput_i_LayMaxDeg1_get(swigCPtr);
      return ret;
    } 
  }

  public int i_LayMaxDeg2 {
    set {
      FOFEMPINVOKE.SoilDataOutput_i_LayMaxDeg2_set(swigCPtr, value);
    } 
    get {
      int ret = FOFEMPINVOKE.SoilDataOutput_i_LayMaxDeg2_get(swigCPtr);
      return ret;
    } 
  }

  public string cr_Model {
    set {
      FOFEMPINVOKE.SoilDataOutput_cr_Model_set(swigCPtr, value);
    } 
    get {
      string ret = FOFEMPINVOKE.SoilDataOutput_cr_Model_get(swigCPtr);
      return ret;
    } 
  }

  public SoilDataOutput() : this(FOFEMPINVOKE.new_SoilDataOutput(), true) {
  }

}

}
