//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NFDRS4 {

public class DeadFuelMoisture : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DeadFuelMoisture(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DeadFuelMoisture obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(DeadFuelMoisture obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~DeadFuelMoisture() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NFDRS4corePINVOKE.delete_DeadFuelMoisture(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public DeadFuelMoisture(double radius, string name) : this(NFDRS4corePINVOKE.new_DeadFuelMoisture__SWIG_0(radius, name), true) {
    if (NFDRS4corePINVOKE.SWIGPendingException.Pending) throw NFDRS4corePINVOKE.SWIGPendingException.Retrieve();
  }

  public DeadFuelMoisture(double radius) : this(NFDRS4corePINVOKE.new_DeadFuelMoisture__SWIG_1(radius), true) {
  }

  public DeadFuelMoisture() : this(NFDRS4corePINVOKE.new_DeadFuelMoisture__SWIG_2(), true) {
  }

  public DeadFuelMoisture(DeadFuelMoisture rhs) : this(NFDRS4corePINVOKE.new_DeadFuelMoisture__SWIG_3(DeadFuelMoisture.getCPtr(rhs)), true) {
    if (NFDRS4corePINVOKE.SWIGPendingException.Pending) throw NFDRS4corePINVOKE.SWIGPendingException.Retrieve();
  }

  public string className() {
    string ret = NFDRS4corePINVOKE.DeadFuelMoisture_className(swigCPtr);
    return ret;
  }

  public void initDeadFuelMoisture1() {
    NFDRS4corePINVOKE.DeadFuelMoisture_initDeadFuelMoisture1(swigCPtr);
  }

  public void initDeadFuelMoisture10() {
    NFDRS4corePINVOKE.DeadFuelMoisture_initDeadFuelMoisture10(swigCPtr);
  }

  public void initDeadFuelMoisture100() {
    NFDRS4corePINVOKE.DeadFuelMoisture_initDeadFuelMoisture100(swigCPtr);
  }

  public void initDeadFuelMoisture1000() {
    NFDRS4corePINVOKE.DeadFuelMoisture_initDeadFuelMoisture1000(swigCPtr);
  }

  public static DeadFuelMoisture createDeadFuelMoisture1(string name) {
    global::System.IntPtr cPtr = NFDRS4corePINVOKE.DeadFuelMoisture_createDeadFuelMoisture1__SWIG_0(name);
    DeadFuelMoisture ret = (cPtr == global::System.IntPtr.Zero) ? null : new DeadFuelMoisture(cPtr, false);
    if (NFDRS4corePINVOKE.SWIGPendingException.Pending) throw NFDRS4corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static DeadFuelMoisture createDeadFuelMoisture1() {
    global::System.IntPtr cPtr = NFDRS4corePINVOKE.DeadFuelMoisture_createDeadFuelMoisture1__SWIG_1();
    DeadFuelMoisture ret = (cPtr == global::System.IntPtr.Zero) ? null : new DeadFuelMoisture(cPtr, false);
    return ret;
  }

  public static DeadFuelMoisture createDeadFuelMoisture10(string name) {
    global::System.IntPtr cPtr = NFDRS4corePINVOKE.DeadFuelMoisture_createDeadFuelMoisture10__SWIG_0(name);
    DeadFuelMoisture ret = (cPtr == global::System.IntPtr.Zero) ? null : new DeadFuelMoisture(cPtr, false);
    if (NFDRS4corePINVOKE.SWIGPendingException.Pending) throw NFDRS4corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static DeadFuelMoisture createDeadFuelMoisture10() {
    global::System.IntPtr cPtr = NFDRS4corePINVOKE.DeadFuelMoisture_createDeadFuelMoisture10__SWIG_1();
    DeadFuelMoisture ret = (cPtr == global::System.IntPtr.Zero) ? null : new DeadFuelMoisture(cPtr, false);
    return ret;
  }

  public static DeadFuelMoisture createDeadFuelMoisture100(string name) {
    global::System.IntPtr cPtr = NFDRS4corePINVOKE.DeadFuelMoisture_createDeadFuelMoisture100__SWIG_0(name);
    DeadFuelMoisture ret = (cPtr == global::System.IntPtr.Zero) ? null : new DeadFuelMoisture(cPtr, false);
    if (NFDRS4corePINVOKE.SWIGPendingException.Pending) throw NFDRS4corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static DeadFuelMoisture createDeadFuelMoisture100() {
    global::System.IntPtr cPtr = NFDRS4corePINVOKE.DeadFuelMoisture_createDeadFuelMoisture100__SWIG_1();
    DeadFuelMoisture ret = (cPtr == global::System.IntPtr.Zero) ? null : new DeadFuelMoisture(cPtr, false);
    return ret;
  }

  public static DeadFuelMoisture createDeadFuelMoisture1000(string name) {
    global::System.IntPtr cPtr = NFDRS4corePINVOKE.DeadFuelMoisture_createDeadFuelMoisture1000__SWIG_0(name);
    DeadFuelMoisture ret = (cPtr == global::System.IntPtr.Zero) ? null : new DeadFuelMoisture(cPtr, false);
    if (NFDRS4corePINVOKE.SWIGPendingException.Pending) throw NFDRS4corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static DeadFuelMoisture createDeadFuelMoisture1000() {
    global::System.IntPtr cPtr = NFDRS4corePINVOKE.DeadFuelMoisture_createDeadFuelMoisture1000__SWIG_1();
    DeadFuelMoisture ret = (cPtr == global::System.IntPtr.Zero) ? null : new DeadFuelMoisture(cPtr, false);
    return ret;
  }

  public static double deriveAdsorptionRate(double radius) {
    double ret = NFDRS4corePINVOKE.DeadFuelMoisture_deriveAdsorptionRate(radius);
    return ret;
  }

  public static int deriveDiffusivitySteps(double radius) {
    int ret = NFDRS4corePINVOKE.DeadFuelMoisture_deriveDiffusivitySteps(radius);
    return ret;
  }

  public static int deriveMoistureSteps(double radius) {
    int ret = NFDRS4corePINVOKE.DeadFuelMoisture_deriveMoistureSteps(radius);
    return ret;
  }

  public static double derivePlanarHeatTransferRate(double radius) {
    double ret = NFDRS4corePINVOKE.DeadFuelMoisture_derivePlanarHeatTransferRate(radius);
    return ret;
  }

  public static double deriveRainfallRunoffFactor(double radius) {
    double ret = NFDRS4corePINVOKE.DeadFuelMoisture_deriveRainfallRunoffFactor(radius);
    return ret;
  }

  public static int deriveStickNodes(double radius) {
    int ret = NFDRS4corePINVOKE.DeadFuelMoisture_deriveStickNodes(radius);
    return ret;
  }

  public static double uniformRandom(double min, double max) {
    double ret = NFDRS4corePINVOKE.DeadFuelMoisture_uniformRandom(min, max);
    return ret;
  }

  public void initializeEnvironment(int year, int month, int day, int hour, int minute, int second, double at, double rh, double sr, double rcum, double ti, double hi, double wi, double bp) {
    NFDRS4corePINVOKE.DeadFuelMoisture_initializeEnvironment__SWIG_0(swigCPtr, year, month, day, hour, minute, second, at, rh, sr, rcum, ti, hi, wi, bp);
  }

  public void initializeEnvironment(int year, int month, int day, int hour, int minute, int second, double at, double rh, double sr, double rcum, double ti, double hi, double wi) {
    NFDRS4corePINVOKE.DeadFuelMoisture_initializeEnvironment__SWIG_1(swigCPtr, year, month, day, hour, minute, second, at, rh, sr, rcum, ti, hi, wi);
  }

  public void initializeEnvironment(double at, double rh, double sr, double rcum, double ti, double hi, double wi, double bp) {
    NFDRS4corePINVOKE.DeadFuelMoisture_initializeEnvironment__SWIG_2(swigCPtr, at, rh, sr, rcum, ti, hi, wi, bp);
  }

  public void initializeEnvironment(double at, double rh, double sr, double rcum, double ti, double hi, double wi) {
    NFDRS4corePINVOKE.DeadFuelMoisture_initializeEnvironment__SWIG_3(swigCPtr, at, rh, sr, rcum, ti, hi, wi);
  }

  public bool update(int year, int month, int day, int hour, int minute, int second, double at, double rh, double sW, double rcum, double bpr, bool prcpAsAmnt) {
    bool ret = NFDRS4corePINVOKE.DeadFuelMoisture_update__SWIG_0(swigCPtr, year, month, day, hour, minute, second, at, rh, sW, rcum, bpr, prcpAsAmnt);
    return ret;
  }

  public bool update(int year, int month, int day, int hour, int minute, int second, double at, double rh, double sW, double rcum, double bpr) {
    bool ret = NFDRS4corePINVOKE.DeadFuelMoisture_update__SWIG_1(swigCPtr, year, month, day, hour, minute, second, at, rh, sW, rcum, bpr);
    return ret;
  }

  public bool update(int year, int month, int day, int hour, int minute, int second, double at, double rh, double sW, double rcum) {
    bool ret = NFDRS4corePINVOKE.DeadFuelMoisture_update__SWIG_2(swigCPtr, year, month, day, hour, minute, second, at, rh, sW, rcum);
    return ret;
  }

  public bool update(double et, double at, double rh, double sW, double rcum, double bpr, bool prcpAsAmnt) {
    bool ret = NFDRS4corePINVOKE.DeadFuelMoisture_update__SWIG_3(swigCPtr, et, at, rh, sW, rcum, bpr, prcpAsAmnt);
    return ret;
  }

  public bool update(double et, double at, double rh, double sW, double rcum, double bpr) {
    bool ret = NFDRS4corePINVOKE.DeadFuelMoisture_update__SWIG_4(swigCPtr, et, at, rh, sW, rcum, bpr);
    return ret;
  }

  public bool update(double et, double at, double rh, double sW, double rcum) {
    bool ret = NFDRS4corePINVOKE.DeadFuelMoisture_update__SWIG_5(swigCPtr, et, at, rh, sW, rcum);
    return ret;
  }

  public void zero() {
    NFDRS4corePINVOKE.DeadFuelMoisture_zero(swigCPtr);
  }

  public double elapsedTime() {
    double ret = NFDRS4corePINVOKE.DeadFuelMoisture_elapsedTime(swigCPtr);
    return ret;
  }

  public bool initialized() {
    bool ret = NFDRS4corePINVOKE.DeadFuelMoisture_initialized(swigCPtr);
    return ret;
  }

  public string name() {
    string ret = NFDRS4corePINVOKE.DeadFuelMoisture_name(swigCPtr);
    return ret;
  }

  public double meanMoisture() {
    double ret = NFDRS4corePINVOKE.DeadFuelMoisture_meanMoisture(swigCPtr);
    return ret;
  }

  public double meanWtdMoisture() {
    double ret = NFDRS4corePINVOKE.DeadFuelMoisture_meanWtdMoisture(swigCPtr);
    return ret;
  }

  public double medianRadialMoisture() {
    double ret = NFDRS4corePINVOKE.DeadFuelMoisture_medianRadialMoisture(swigCPtr);
    return ret;
  }

  public double meanWtdTemperature() {
    double ret = NFDRS4corePINVOKE.DeadFuelMoisture_meanWtdTemperature(swigCPtr);
    return ret;
  }

  public double pptRate() {
    double ret = NFDRS4corePINVOKE.DeadFuelMoisture_pptRate(swigCPtr);
    return ret;
  }

  public int state() {
    int ret = NFDRS4corePINVOKE.DeadFuelMoisture_state(swigCPtr);
    return ret;
  }

  public string stateName() {
    string ret = NFDRS4corePINVOKE.DeadFuelMoisture_stateName(swigCPtr);
    return ret;
  }

  public double surfaceMoisture() {
    double ret = NFDRS4corePINVOKE.DeadFuelMoisture_surfaceMoisture(swigCPtr);
    return ret;
  }

  public double surfaceTemperature() {
    double ret = NFDRS4corePINVOKE.DeadFuelMoisture_surfaceTemperature(swigCPtr);
    return ret;
  }

  public int updates() {
    int ret = NFDRS4corePINVOKE.DeadFuelMoisture_updates(swigCPtr);
    return ret;
  }

  public double adsorptionRate() {
    double ret = NFDRS4corePINVOKE.DeadFuelMoisture_adsorptionRate(swigCPtr);
    return ret;
  }

  public double desorptionRate() {
    double ret = NFDRS4corePINVOKE.DeadFuelMoisture_desorptionRate(swigCPtr);
    return ret;
  }

  public int diffusivitySteps() {
    int ret = NFDRS4corePINVOKE.DeadFuelMoisture_diffusivitySteps(swigCPtr);
    return ret;
  }

  public double maximumLocalMoisture() {
    double ret = NFDRS4corePINVOKE.DeadFuelMoisture_maximumLocalMoisture(swigCPtr);
    return ret;
  }

  public int moistureSteps() {
    int ret = NFDRS4corePINVOKE.DeadFuelMoisture_moistureSteps(swigCPtr);
    return ret;
  }

  public double planarHeatTransferRate() {
    double ret = NFDRS4corePINVOKE.DeadFuelMoisture_planarHeatTransferRate(swigCPtr);
    return ret;
  }

  public double rainfallRunoffFactor() {
    double ret = NFDRS4corePINVOKE.DeadFuelMoisture_rainfallRunoffFactor(swigCPtr);
    return ret;
  }

  public double stickDensity() {
    double ret = NFDRS4corePINVOKE.DeadFuelMoisture_stickDensity(swigCPtr);
    return ret;
  }

  public double stickLength() {
    double ret = NFDRS4corePINVOKE.DeadFuelMoisture_stickLength(swigCPtr);
    return ret;
  }

  public int stickNodes() {
    int ret = NFDRS4corePINVOKE.DeadFuelMoisture_stickNodes(swigCPtr);
    return ret;
  }

  public double waterFilmContribution() {
    double ret = NFDRS4corePINVOKE.DeadFuelMoisture_waterFilmContribution(swigCPtr);
    return ret;
  }

  public void initializeStick() {
    NFDRS4corePINVOKE.DeadFuelMoisture_initializeStick(swigCPtr);
  }

  public void setAdsorptionRate(double adsorptionRate) {
    NFDRS4corePINVOKE.DeadFuelMoisture_setAdsorptionRate(swigCPtr, adsorptionRate);
  }

  public void setAllowRainstorm(bool allow) {
    NFDRS4corePINVOKE.DeadFuelMoisture_setAllowRainstorm__SWIG_0(swigCPtr, allow);
  }

  public void setAllowRainstorm() {
    NFDRS4corePINVOKE.DeadFuelMoisture_setAllowRainstorm__SWIG_1(swigCPtr);
  }

  public void setAllowRainfall2(bool allow) {
    NFDRS4corePINVOKE.DeadFuelMoisture_setAllowRainfall2__SWIG_0(swigCPtr, allow);
  }

  public void setAllowRainfall2() {
    NFDRS4corePINVOKE.DeadFuelMoisture_setAllowRainfall2__SWIG_1(swigCPtr);
  }

  public void setDesorptionRate(double desorptionRate) {
    NFDRS4corePINVOKE.DeadFuelMoisture_setDesorptionRate__SWIG_0(swigCPtr, desorptionRate);
  }

  public void setDesorptionRate() {
    NFDRS4corePINVOKE.DeadFuelMoisture_setDesorptionRate__SWIG_1(swigCPtr);
  }

  public void setDiffusivitySteps(int diffusivitySteps) {
    NFDRS4corePINVOKE.DeadFuelMoisture_setDiffusivitySteps(swigCPtr, diffusivitySteps);
  }

  public void setMaximumLocalMoisture(double localMaxMc) {
    NFDRS4corePINVOKE.DeadFuelMoisture_setMaximumLocalMoisture__SWIG_0(swigCPtr, localMaxMc);
  }

  public void setMaximumLocalMoisture() {
    NFDRS4corePINVOKE.DeadFuelMoisture_setMaximumLocalMoisture__SWIG_1(swigCPtr);
  }

  public void setMoistureSteps(int moistureSteps) {
    NFDRS4corePINVOKE.DeadFuelMoisture_setMoistureSteps(swigCPtr, moistureSteps);
  }

  public void setPertubateColumn(bool pertubate) {
    NFDRS4corePINVOKE.DeadFuelMoisture_setPertubateColumn__SWIG_0(swigCPtr, pertubate);
  }

  public void setPertubateColumn() {
    NFDRS4corePINVOKE.DeadFuelMoisture_setPertubateColumn__SWIG_1(swigCPtr);
  }

  public void setPlanarHeatTransferRate(double planarHeatTransferRate) {
    NFDRS4corePINVOKE.DeadFuelMoisture_setPlanarHeatTransferRate(swigCPtr, planarHeatTransferRate);
  }

  public void setRainfallRunoffFactor(double rainfallRunoffFactor) {
    NFDRS4corePINVOKE.DeadFuelMoisture_setRainfallRunoffFactor(swigCPtr, rainfallRunoffFactor);
  }

  public void setRandomSeed(int randseed) {
    NFDRS4corePINVOKE.DeadFuelMoisture_setRandomSeed__SWIG_0(swigCPtr, randseed);
  }

  public void setRandomSeed() {
    NFDRS4corePINVOKE.DeadFuelMoisture_setRandomSeed__SWIG_1(swigCPtr);
  }

  public void setRampRai0(bool ramp) {
    NFDRS4corePINVOKE.DeadFuelMoisture_setRampRai0__SWIG_0(swigCPtr, ramp);
  }

  public void setRampRai0() {
    NFDRS4corePINVOKE.DeadFuelMoisture_setRampRai0__SWIG_1(swigCPtr);
  }

  public void setStickDensity(double stickDensity) {
    NFDRS4corePINVOKE.DeadFuelMoisture_setStickDensity__SWIG_0(swigCPtr, stickDensity);
  }

  public void setStickDensity() {
    NFDRS4corePINVOKE.DeadFuelMoisture_setStickDensity__SWIG_1(swigCPtr);
  }

  public void setStickLength(double stickLength) {
    NFDRS4corePINVOKE.DeadFuelMoisture_setStickLength__SWIG_0(swigCPtr, stickLength);
  }

  public void setStickLength() {
    NFDRS4corePINVOKE.DeadFuelMoisture_setStickLength__SWIG_1(swigCPtr);
  }

  public void setStickNodes(int stickNodes) {
    NFDRS4corePINVOKE.DeadFuelMoisture_setStickNodes__SWIG_0(swigCPtr, stickNodes);
  }

  public void setStickNodes() {
    NFDRS4corePINVOKE.DeadFuelMoisture_setStickNodes__SWIG_1(swigCPtr);
  }

  public void setWaterFilmContribution(double waterFilm) {
    NFDRS4corePINVOKE.DeadFuelMoisture_setWaterFilmContribution__SWIG_0(swigCPtr, waterFilm);
  }

  public void setWaterFilmContribution() {
    NFDRS4corePINVOKE.DeadFuelMoisture_setWaterFilmContribution__SWIG_1(swigCPtr);
  }

  public void setMoisture(float initFM) {
    NFDRS4corePINVOKE.DeadFuelMoisture_setMoisture(swigCPtr, initFM);
  }

  public double eqmc(double fTemp, double fRH) {
    double ret = NFDRS4corePINVOKE.DeadFuelMoisture_eqmc(swigCPtr, fTemp, fRH);
    return ret;
  }

  public void initializeParameters(double radius, string name) {
    NFDRS4corePINVOKE.DeadFuelMoisture_initializeParameters(swigCPtr, radius, name);
    if (NFDRS4corePINVOKE.SWIGPendingException.Pending) throw NFDRS4corePINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_DFMCalcState GetState() {
    SWIGTYPE_p_DFMCalcState ret = new SWIGTYPE_p_DFMCalcState(NFDRS4corePINVOKE.DeadFuelMoisture_GetState(swigCPtr), true);
    return ret;
  }

  public bool SetState(SWIGTYPE_p_DFMCalcState state) {
    bool ret = NFDRS4corePINVOKE.DeadFuelMoisture_SetState(swigCPtr, SWIGTYPE_p_DFMCalcState.getCPtr(state));
    if (NFDRS4corePINVOKE.SWIGPendingException.Pending) throw NFDRS4corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
