//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NFDRS4 {

public enum DFM_State {
  DFM_State_None = 0,
  DFM_State_Adsorption = 1,
  DFM_State_Desorption = 2,
  DFM_State_Condensation1 = 3,
  DFM_State_Condensation2 = 4,
  DFM_State_Evaporation = 5,
  DFM_State_Rainfall1 = 6,
  DFM_State_Rainfall2 = 7,
  DFM_State_Rainstorm = 8,
  DFM_State_Stagnation = 9,
  DFM_State_Error = 10
}

}
