//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NFDRS4 {

public class LiveFuelMoisture : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LiveFuelMoisture(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LiveFuelMoisture obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(LiveFuelMoisture obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~LiveFuelMoisture() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NFDRS4corePINVOKE.delete_LiveFuelMoisture(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public LiveFuelMoisture() : this(NFDRS4corePINVOKE.new_LiveFuelMoisture__SWIG_0(), true) {
  }

  public LiveFuelMoisture(double Lat, bool IsHerb, bool IsAnnual) : this(NFDRS4corePINVOKE.new_LiveFuelMoisture__SWIG_1(Lat, IsHerb, IsAnnual), true) {
  }

  public void Initialize(double Lat, bool IsHerb, bool IsAnnual) {
    NFDRS4corePINVOKE.LiveFuelMoisture_Initialize(swigCPtr, Lat, IsHerb, IsAnnual);
  }

  public void SetLimits(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, double arg6, double arg7) {
    NFDRS4corePINVOKE.LiveFuelMoisture_SetLimits(swigCPtr, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
  }

  public void Update(double TempF, double MaxTempF, double MinTempF, double RH, double minRH, int Jday, double RTPrcp, SWIGTYPE_p_time_t thisTime) {
    NFDRS4corePINVOKE.LiveFuelMoisture_Update(swigCPtr, TempF, MaxTempF, MinTempF, RH, minRH, Jday, RTPrcp, SWIGTYPE_p_time_t.getCPtr(thisTime));
    if (NFDRS4corePINVOKE.SWIGPendingException.Pending) throw NFDRS4corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetMAPeriod(uint MAPeriod) {
    NFDRS4corePINVOKE.LiveFuelMoisture_SetMAPeriod(swigCPtr, MAPeriod);
  }

  public void SetLFMParameters(double MaxGSI, double GreenupThreshold, double MinLFMVal, double MaxLFMVal) {
    NFDRS4corePINVOKE.LiveFuelMoisture_SetLFMParameters(swigCPtr, MaxGSI, GreenupThreshold, MinLFMVal, MaxLFMVal);
  }

  public void GetLFMParameters(SWIGTYPE_p_double MaxGSI, SWIGTYPE_p_double GreenupThreshold, SWIGTYPE_p_double MinLFMVal, SWIGTYPE_p_double MaxLFMVal) {
    NFDRS4corePINVOKE.LiveFuelMoisture_GetLFMParameters(swigCPtr, SWIGTYPE_p_double.getCPtr(MaxGSI), SWIGTYPE_p_double.getCPtr(GreenupThreshold), SWIGTYPE_p_double.getCPtr(MinLFMVal), SWIGTYPE_p_double.getCPtr(MaxLFMVal));
  }

  public void SetNumPrecipDays(int numDays) {
    NFDRS4corePINVOKE.LiveFuelMoisture_SetNumPrecipDays(swigCPtr, numDays);
  }

  public int GetNumPrecipDays() {
    int ret = NFDRS4corePINVOKE.LiveFuelMoisture_GetNumPrecipDays(swigCPtr);
    return ret;
  }

  public double GetMoisture(bool SnowDay) {
    double ret = NFDRS4corePINVOKE.LiveFuelMoisture_GetMoisture__SWIG_0(swigCPtr, SnowDay);
    return ret;
  }

  public double GetMoisture() {
    double ret = NFDRS4corePINVOKE.LiveFuelMoisture_GetMoisture__SWIG_1(swigCPtr);
    return ret;
  }

  public double CalcRunningAvgGSI() {
    double ret = NFDRS4corePINVOKE.LiveFuelMoisture_CalcRunningAvgGSI(swigCPtr);
    return ret;
  }

  public double CalcRunningAvgHerbFM(bool SnowDay) {
    double ret = NFDRS4corePINVOKE.LiveFuelMoisture_CalcRunningAvgHerbFM__SWIG_0(swigCPtr, SnowDay);
    return ret;
  }

  public double CalcRunningAvgHerbFM() {
    double ret = NFDRS4corePINVOKE.LiveFuelMoisture_CalcRunningAvgHerbFM__SWIG_1(swigCPtr);
    return ret;
  }

  public void ResetHerbState() {
    NFDRS4corePINVOKE.LiveFuelMoisture_ResetHerbState(swigCPtr);
  }

  public double CalcRunningAvgWoodyFM(bool SnowDay) {
    double ret = NFDRS4corePINVOKE.LiveFuelMoisture_CalcRunningAvgWoodyFM__SWIG_0(swigCPtr, SnowDay);
    return ret;
  }

  public double CalcRunningAvgWoodyFM() {
    double ret = NFDRS4corePINVOKE.LiveFuelMoisture_CalcRunningAvgWoodyFM__SWIG_1(swigCPtr);
    return ret;
  }

  public double CalcGSI(double minRH, double maxTempF, double minTempF, double RTPrcp, double lat, int doy) {
    double ret = NFDRS4corePINVOKE.LiveFuelMoisture_CalcGSI(swigCPtr, minRH, maxTempF, minTempF, RTPrcp, lat, doy);
    return ret;
  }

  public double CalcGSI_VPDAvg(double RH, double TempF, double maxTempF, double minTempF, double RTPrcp, double lat, int doy) {
    double ret = NFDRS4corePINVOKE.LiveFuelMoisture_CalcGSI_VPDAvg(swigCPtr, RH, TempF, maxTempF, minTempF, RTPrcp, lat, doy);
    return ret;
  }

  public double GetTminInd(double Tmin) {
    double ret = NFDRS4corePINVOKE.LiveFuelMoisture_GetTminInd(swigCPtr, Tmin);
    return ret;
  }

  public double GetVPDInd(double VPD) {
    double ret = NFDRS4corePINVOKE.LiveFuelMoisture_GetVPDInd(swigCPtr, VPD);
    return ret;
  }

  public double GetDaylInd(double Dayl) {
    double ret = NFDRS4corePINVOKE.LiveFuelMoisture_GetDaylInd(swigCPtr, Dayl);
    return ret;
  }

  public double GetPrcpInd(double RTPrcp) {
    double ret = NFDRS4corePINVOKE.LiveFuelMoisture_GetPrcpInd(swigCPtr, RTPrcp);
    return ret;
  }

  public double CalcDayl(double lat, int yday) {
    double ret = NFDRS4corePINVOKE.LiveFuelMoisture_CalcDayl(swigCPtr, lat, yday);
    return ret;
  }

  public double CalcVPDavg(double TempDewF, double TempAvgF) {
    double ret = NFDRS4corePINVOKE.LiveFuelMoisture_CalcVPDavg(swigCPtr, TempDewF, TempAvgF);
    return ret;
  }

  public double CalcVPD(double RH, double TempF) {
    double ret = NFDRS4corePINVOKE.LiveFuelMoisture_CalcVPD(swigCPtr, RH, TempF);
    return ret;
  }

  public double CalcDPT(double tempF, double RH) {
    double ret = NFDRS4corePINVOKE.LiveFuelMoisture_CalcDPT(swigCPtr, tempF, RH);
    return ret;
  }

  public double CalcVP(double tempF) {
    double ret = NFDRS4corePINVOKE.LiveFuelMoisture_CalcVP(swigCPtr, tempF);
    return ret;
  }

  public double GetMaxGSI() {
    double ret = NFDRS4corePINVOKE.LiveFuelMoisture_GetMaxGSI(swigCPtr);
    return ret;
  }

  public double GetGreenupThreshold() {
    double ret = NFDRS4corePINVOKE.LiveFuelMoisture_GetGreenupThreshold(swigCPtr);
    return ret;
  }

  public double GetMinLFMVal() {
    double ret = NFDRS4corePINVOKE.LiveFuelMoisture_GetMinLFMVal(swigCPtr);
    return ret;
  }

  public double GetMaxLFMVal() {
    double ret = NFDRS4corePINVOKE.LiveFuelMoisture_GetMaxLFMVal(swigCPtr);
    return ret;
  }

  public void SetUseVPDAvg(bool set) {
    NFDRS4corePINVOKE.LiveFuelMoisture_SetUseVPDAvg(swigCPtr, set);
  }

  public bool GetUseVPDAvg() {
    bool ret = NFDRS4corePINVOKE.LiveFuelMoisture_GetUseVPDAvg(swigCPtr);
    return ret;
  }

  public bool GetIsAnnual() {
    bool ret = NFDRS4corePINVOKE.LiveFuelMoisture_GetIsAnnual(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_LFMCalcState GetState() {
    SWIGTYPE_p_LFMCalcState ret = new SWIGTYPE_p_LFMCalcState(NFDRS4corePINVOKE.LiveFuelMoisture_GetState(swigCPtr), true);
    return ret;
  }

  public bool SetState(SWIGTYPE_p_LFMCalcState state) {
    bool ret = NFDRS4corePINVOKE.LiveFuelMoisture_SetState(swigCPtr, SWIGTYPE_p_LFMCalcState.getCPtr(state));
    if (NFDRS4corePINVOKE.SWIGPendingException.Pending) throw NFDRS4corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetUseRTPrecip(bool set) {
    NFDRS4corePINVOKE.LiveFuelMoisture_SetUseRTPrecip(swigCPtr, set);
  }

  public bool GetUseRTPrecip() {
    bool ret = NFDRS4corePINVOKE.LiveFuelMoisture_GetUseRTPrecip(swigCPtr);
    return ret;
  }

}

}
