//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NFDRS4 {

class NFDRS4corePINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="SWIGRegisterExceptionCallbacks_NFDRS4core")]
    public static extern void SWIGRegisterExceptionCallbacks_NFDRS4core(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_NFDRS4core")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_NFDRS4core(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_NFDRS4core(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_NFDRS4core(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="SWIGRegisterStringCallback_NFDRS4core")]
    public static extern void SWIGRegisterStringCallback_NFDRS4core(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_NFDRS4core(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  public class SWIGStringWithLengthHelper {

    [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="SWIG_csharp_string_to_c")]
    private static extern global::System.IntPtr SWIG_csharp_string_to_c0(int size, int len, [global::System.Runtime.InteropServices.In,global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr, SizeParamIndex=0)] string str);

    [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="SWIG_csharp_string_size")]
    private static extern int SWIG_csharp_string_size(global::System.IntPtr str);

    [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="SWIG_csharp_string_str")]
    private static extern global::System.IntPtr SWIG_csharp_string_str(global::System.IntPtr str);

    public static global::System.IntPtr SWIG_csharp_string_to_c(string str) {
      if (str == null)
        return global::System.IntPtr.Zero;
      global::System.Text.Encoding utf8 = global::System.Text.Encoding.UTF8;
      return SWIG_csharp_string_to_c0(utf8.GetByteCount(str), str.Length, str);
    }

    public static string SWIG_c_to_csharp_string(global::System.IntPtr str) {
      int size = SWIG_csharp_string_size(str);
      if (size > 0) {
        global::System.IntPtr s = SWIG_csharp_string_str(str);
        byte[] b = new byte[size];
        global::System.Runtime.InteropServices.Marshal.Copy(s, b, 0, size);
        global::System.Text.Encoding utf8 = global::System.Text.Encoding.UTF8;
        return utf8.GetString(b);
      }
      return null;
    }
  }


  static NFDRS4corePINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_new_DeadFuelMoisture__SWIG_0")]
  public static extern global::System.IntPtr new_DeadFuelMoisture__SWIG_0(double jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_new_DeadFuelMoisture__SWIG_1")]
  public static extern global::System.IntPtr new_DeadFuelMoisture__SWIG_1(double jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_new_DeadFuelMoisture__SWIG_2")]
  public static extern global::System.IntPtr new_DeadFuelMoisture__SWIG_2();

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_delete_DeadFuelMoisture")]
  public static extern void delete_DeadFuelMoisture(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_new_DeadFuelMoisture__SWIG_3")]
  public static extern global::System.IntPtr new_DeadFuelMoisture__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_className")]
  public static extern string DeadFuelMoisture_className(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_initDeadFuelMoisture1")]
  public static extern void DeadFuelMoisture_initDeadFuelMoisture1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_initDeadFuelMoisture10")]
  public static extern void DeadFuelMoisture_initDeadFuelMoisture10(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_initDeadFuelMoisture100")]
  public static extern void DeadFuelMoisture_initDeadFuelMoisture100(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_initDeadFuelMoisture1000")]
  public static extern void DeadFuelMoisture_initDeadFuelMoisture1000(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_createDeadFuelMoisture1__SWIG_0")]
  public static extern global::System.IntPtr DeadFuelMoisture_createDeadFuelMoisture1__SWIG_0(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_createDeadFuelMoisture1__SWIG_1")]
  public static extern global::System.IntPtr DeadFuelMoisture_createDeadFuelMoisture1__SWIG_1();

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_createDeadFuelMoisture10__SWIG_0")]
  public static extern global::System.IntPtr DeadFuelMoisture_createDeadFuelMoisture10__SWIG_0(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_createDeadFuelMoisture10__SWIG_1")]
  public static extern global::System.IntPtr DeadFuelMoisture_createDeadFuelMoisture10__SWIG_1();

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_createDeadFuelMoisture100__SWIG_0")]
  public static extern global::System.IntPtr DeadFuelMoisture_createDeadFuelMoisture100__SWIG_0(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_createDeadFuelMoisture100__SWIG_1")]
  public static extern global::System.IntPtr DeadFuelMoisture_createDeadFuelMoisture100__SWIG_1();

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_createDeadFuelMoisture1000__SWIG_0")]
  public static extern global::System.IntPtr DeadFuelMoisture_createDeadFuelMoisture1000__SWIG_0(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_createDeadFuelMoisture1000__SWIG_1")]
  public static extern global::System.IntPtr DeadFuelMoisture_createDeadFuelMoisture1000__SWIG_1();

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_deriveAdsorptionRate")]
  public static extern double DeadFuelMoisture_deriveAdsorptionRate(double jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_deriveDiffusivitySteps")]
  public static extern int DeadFuelMoisture_deriveDiffusivitySteps(double jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_deriveMoistureSteps")]
  public static extern int DeadFuelMoisture_deriveMoistureSteps(double jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_derivePlanarHeatTransferRate")]
  public static extern double DeadFuelMoisture_derivePlanarHeatTransferRate(double jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_deriveRainfallRunoffFactor")]
  public static extern double DeadFuelMoisture_deriveRainfallRunoffFactor(double jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_deriveStickNodes")]
  public static extern int DeadFuelMoisture_deriveStickNodes(double jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_uniformRandom")]
  public static extern double DeadFuelMoisture_uniformRandom(double jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_initializeEnvironment__SWIG_0")]
  public static extern void DeadFuelMoisture_initializeEnvironment__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7, double jarg8, double jarg9, double jarg10, double jarg11, double jarg12, double jarg13, double jarg14, double jarg15);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_initializeEnvironment__SWIG_1")]
  public static extern void DeadFuelMoisture_initializeEnvironment__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7, double jarg8, double jarg9, double jarg10, double jarg11, double jarg12, double jarg13, double jarg14);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_initializeEnvironment__SWIG_2")]
  public static extern void DeadFuelMoisture_initializeEnvironment__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3, double jarg4, double jarg5, double jarg6, double jarg7, double jarg8, double jarg9);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_initializeEnvironment__SWIG_3")]
  public static extern void DeadFuelMoisture_initializeEnvironment__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3, double jarg4, double jarg5, double jarg6, double jarg7, double jarg8);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_update__SWIG_0")]
  public static extern bool DeadFuelMoisture_update__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7, double jarg8, double jarg9, double jarg10, double jarg11, double jarg12, bool jarg13);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_update__SWIG_1")]
  public static extern bool DeadFuelMoisture_update__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7, double jarg8, double jarg9, double jarg10, double jarg11, double jarg12);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_update__SWIG_2")]
  public static extern bool DeadFuelMoisture_update__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7, double jarg8, double jarg9, double jarg10, double jarg11);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_update__SWIG_3")]
  public static extern bool DeadFuelMoisture_update__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3, double jarg4, double jarg5, double jarg6, double jarg7, bool jarg8);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_update__SWIG_4")]
  public static extern bool DeadFuelMoisture_update__SWIG_4(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3, double jarg4, double jarg5, double jarg6, double jarg7);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_update__SWIG_5")]
  public static extern bool DeadFuelMoisture_update__SWIG_5(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3, double jarg4, double jarg5, double jarg6);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_zero")]
  public static extern void DeadFuelMoisture_zero(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_elapsedTime")]
  public static extern double DeadFuelMoisture_elapsedTime(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_initialized")]
  public static extern bool DeadFuelMoisture_initialized(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_name")]
  public static extern string DeadFuelMoisture_name(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_meanMoisture")]
  public static extern double DeadFuelMoisture_meanMoisture(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_meanWtdMoisture")]
  public static extern double DeadFuelMoisture_meanWtdMoisture(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_medianRadialMoisture")]
  public static extern double DeadFuelMoisture_medianRadialMoisture(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_meanWtdTemperature")]
  public static extern double DeadFuelMoisture_meanWtdTemperature(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_pptRate")]
  public static extern double DeadFuelMoisture_pptRate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_state")]
  public static extern int DeadFuelMoisture_state(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_stateName")]
  public static extern string DeadFuelMoisture_stateName(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_surfaceMoisture")]
  public static extern double DeadFuelMoisture_surfaceMoisture(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_surfaceTemperature")]
  public static extern double DeadFuelMoisture_surfaceTemperature(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_updates")]
  public static extern int DeadFuelMoisture_updates(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_adsorptionRate")]
  public static extern double DeadFuelMoisture_adsorptionRate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_desorptionRate")]
  public static extern double DeadFuelMoisture_desorptionRate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_diffusivitySteps")]
  public static extern int DeadFuelMoisture_diffusivitySteps(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_maximumLocalMoisture")]
  public static extern double DeadFuelMoisture_maximumLocalMoisture(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_moistureSteps")]
  public static extern int DeadFuelMoisture_moistureSteps(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_planarHeatTransferRate")]
  public static extern double DeadFuelMoisture_planarHeatTransferRate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_rainfallRunoffFactor")]
  public static extern double DeadFuelMoisture_rainfallRunoffFactor(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_stickDensity")]
  public static extern double DeadFuelMoisture_stickDensity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_stickLength")]
  public static extern double DeadFuelMoisture_stickLength(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_stickNodes")]
  public static extern int DeadFuelMoisture_stickNodes(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_waterFilmContribution")]
  public static extern double DeadFuelMoisture_waterFilmContribution(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_initializeStick")]
  public static extern void DeadFuelMoisture_initializeStick(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setAdsorptionRate")]
  public static extern void DeadFuelMoisture_setAdsorptionRate(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setAllowRainstorm__SWIG_0")]
  public static extern void DeadFuelMoisture_setAllowRainstorm__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setAllowRainstorm__SWIG_1")]
  public static extern void DeadFuelMoisture_setAllowRainstorm__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setAllowRainfall2__SWIG_0")]
  public static extern void DeadFuelMoisture_setAllowRainfall2__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setAllowRainfall2__SWIG_1")]
  public static extern void DeadFuelMoisture_setAllowRainfall2__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setDesorptionRate__SWIG_0")]
  public static extern void DeadFuelMoisture_setDesorptionRate__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setDesorptionRate__SWIG_1")]
  public static extern void DeadFuelMoisture_setDesorptionRate__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setDiffusivitySteps")]
  public static extern void DeadFuelMoisture_setDiffusivitySteps(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setMaximumLocalMoisture__SWIG_0")]
  public static extern void DeadFuelMoisture_setMaximumLocalMoisture__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setMaximumLocalMoisture__SWIG_1")]
  public static extern void DeadFuelMoisture_setMaximumLocalMoisture__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setMoistureSteps")]
  public static extern void DeadFuelMoisture_setMoistureSteps(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setPertubateColumn__SWIG_0")]
  public static extern void DeadFuelMoisture_setPertubateColumn__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setPertubateColumn__SWIG_1")]
  public static extern void DeadFuelMoisture_setPertubateColumn__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setPlanarHeatTransferRate")]
  public static extern void DeadFuelMoisture_setPlanarHeatTransferRate(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setRainfallRunoffFactor")]
  public static extern void DeadFuelMoisture_setRainfallRunoffFactor(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setRandomSeed__SWIG_0")]
  public static extern void DeadFuelMoisture_setRandomSeed__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setRandomSeed__SWIG_1")]
  public static extern void DeadFuelMoisture_setRandomSeed__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setRampRai0__SWIG_0")]
  public static extern void DeadFuelMoisture_setRampRai0__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setRampRai0__SWIG_1")]
  public static extern void DeadFuelMoisture_setRampRai0__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setStickDensity__SWIG_0")]
  public static extern void DeadFuelMoisture_setStickDensity__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setStickDensity__SWIG_1")]
  public static extern void DeadFuelMoisture_setStickDensity__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setStickLength__SWIG_0")]
  public static extern void DeadFuelMoisture_setStickLength__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setStickLength__SWIG_1")]
  public static extern void DeadFuelMoisture_setStickLength__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setStickNodes__SWIG_0")]
  public static extern void DeadFuelMoisture_setStickNodes__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setStickNodes__SWIG_1")]
  public static extern void DeadFuelMoisture_setStickNodes__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setWaterFilmContribution__SWIG_0")]
  public static extern void DeadFuelMoisture_setWaterFilmContribution__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setWaterFilmContribution__SWIG_1")]
  public static extern void DeadFuelMoisture_setWaterFilmContribution__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_setMoisture")]
  public static extern void DeadFuelMoisture_setMoisture(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_eqmc")]
  public static extern double DeadFuelMoisture_eqmc(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_initializeParameters")]
  public static extern void DeadFuelMoisture_initializeParameters(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_GetState")]
  public static extern global::System.IntPtr DeadFuelMoisture_GetState(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DeadFuelMoisture_SetState")]
  public static extern bool DeadFuelMoisture_SetState(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_NOVALUE_get")]
  public static extern double NOVALUE_get();

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_RADPERDAY_get")]
  public static extern double RADPERDAY_get();

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_RADPERDEG_get")]
  public static extern double RADPERDEG_get();

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_MINDECL_get")]
  public static extern double MINDECL_get();

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_SECPERRAD_get")]
  public static extern double SECPERRAD_get();

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_DAYSOFF_get")]
  public static extern double DAYSOFF_get();

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_new_LiveFuelMoisture__SWIG_0")]
  public static extern global::System.IntPtr new_LiveFuelMoisture__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_new_LiveFuelMoisture__SWIG_1")]
  public static extern global::System.IntPtr new_LiveFuelMoisture__SWIG_1(double jarg1, bool jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_Initialize")]
  public static extern void LiveFuelMoisture_Initialize(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, bool jarg3, bool jarg4);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_SetLimits")]
  public static extern void LiveFuelMoisture_SetLimits(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3, double jarg4, double jarg5, double jarg6, double jarg7, double jarg8, double jarg9);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_Update")]
  public static extern void LiveFuelMoisture_Update(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3, double jarg4, double jarg5, double jarg6, int jarg7, double jarg8, global::System.Runtime.InteropServices.HandleRef jarg9);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_SetMAPeriod")]
  public static extern void LiveFuelMoisture_SetMAPeriod(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_SetLFMParameters")]
  public static extern void LiveFuelMoisture_SetLFMParameters(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3, double jarg4, double jarg5);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_GetLFMParameters")]
  public static extern void LiveFuelMoisture_GetLFMParameters(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_SetNumPrecipDays")]
  public static extern void LiveFuelMoisture_SetNumPrecipDays(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_GetNumPrecipDays")]
  public static extern int LiveFuelMoisture_GetNumPrecipDays(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_GetMoisture__SWIG_0")]
  public static extern double LiveFuelMoisture_GetMoisture__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_GetMoisture__SWIG_1")]
  public static extern double LiveFuelMoisture_GetMoisture__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_CalcRunningAvgGSI")]
  public static extern double LiveFuelMoisture_CalcRunningAvgGSI(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_CalcRunningAvgHerbFM__SWIG_0")]
  public static extern double LiveFuelMoisture_CalcRunningAvgHerbFM__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_CalcRunningAvgHerbFM__SWIG_1")]
  public static extern double LiveFuelMoisture_CalcRunningAvgHerbFM__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_ResetHerbState")]
  public static extern void LiveFuelMoisture_ResetHerbState(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_CalcRunningAvgWoodyFM__SWIG_0")]
  public static extern double LiveFuelMoisture_CalcRunningAvgWoodyFM__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_CalcRunningAvgWoodyFM__SWIG_1")]
  public static extern double LiveFuelMoisture_CalcRunningAvgWoodyFM__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_CalcGSI")]
  public static extern double LiveFuelMoisture_CalcGSI(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3, double jarg4, double jarg5, double jarg6, int jarg7);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_CalcGSI_VPDAvg")]
  public static extern double LiveFuelMoisture_CalcGSI_VPDAvg(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3, double jarg4, double jarg5, double jarg6, double jarg7, int jarg8);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_GetTminInd")]
  public static extern double LiveFuelMoisture_GetTminInd(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_GetVPDInd")]
  public static extern double LiveFuelMoisture_GetVPDInd(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_GetDaylInd")]
  public static extern double LiveFuelMoisture_GetDaylInd(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_GetPrcpInd")]
  public static extern double LiveFuelMoisture_GetPrcpInd(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_CalcDayl")]
  public static extern double LiveFuelMoisture_CalcDayl(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_CalcVPDavg")]
  public static extern double LiveFuelMoisture_CalcVPDavg(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_CalcVPD")]
  public static extern double LiveFuelMoisture_CalcVPD(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_CalcDPT")]
  public static extern double LiveFuelMoisture_CalcDPT(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_CalcVP")]
  public static extern double LiveFuelMoisture_CalcVP(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_GetMaxGSI")]
  public static extern double LiveFuelMoisture_GetMaxGSI(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_GetGreenupThreshold")]
  public static extern double LiveFuelMoisture_GetGreenupThreshold(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_GetMinLFMVal")]
  public static extern double LiveFuelMoisture_GetMinLFMVal(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_GetMaxLFMVal")]
  public static extern double LiveFuelMoisture_GetMaxLFMVal(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_SetUseVPDAvg")]
  public static extern void LiveFuelMoisture_SetUseVPDAvg(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_GetUseVPDAvg")]
  public static extern bool LiveFuelMoisture_GetUseVPDAvg(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_GetIsAnnual")]
  public static extern bool LiveFuelMoisture_GetIsAnnual(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_GetState")]
  public static extern global::System.IntPtr LiveFuelMoisture_GetState(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_SetState")]
  public static extern bool LiveFuelMoisture_SetState(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_SetUseRTPrecip")]
  public static extern void LiveFuelMoisture_SetUseRTPrecip(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_LiveFuelMoisture_GetUseRTPrecip")]
  public static extern bool LiveFuelMoisture_GetUseRTPrecip(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("NFDRS4core", EntryPoint="CSharp_NFDRS4_delete_LiveFuelMoisture")]
  public static extern void delete_LiveFuelMoisture(global::System.Runtime.InteropServices.HandleRef jarg1);
}

}
