//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace NFDRS4 {

public class NFDRS4core {
  public static readonly double NOVALUE = NFDRS4corePINVOKE.NOVALUE_get();
  public static readonly double RADPERDAY = NFDRS4corePINVOKE.RADPERDAY_get();
  public static readonly double RADPERDEG = NFDRS4corePINVOKE.RADPERDEG_get();
  public static readonly double MINDECL = NFDRS4corePINVOKE.MINDECL_get();
  public static readonly double SECPERRAD = NFDRS4corePINVOKE.SECPERRAD_get();
  public static readonly double DAYSOFF = NFDRS4corePINVOKE.DAYSOFF_get();
}

}
